import Zeta23.CCM.CanonicalSourceEnergy

noncomputable section

namespace Zeta23.CCM

open Matrix Set
open scoped BigOperators ArithmeticFunction ComplexConjugate

/-!
# FIRST-BAD-RIGIDITY-E4-A4b2a: canonical source pairing

PR #136 theorem-locks the scalar-sensitive diagonal canonical energy.  The
one-step determinant also needs the off-diagonal shell/predecessor coupling.
This module exposes that coupling through the same production pole / reduced
archimedean / scalar / prime-source channel matrix without introducing any
sign theorem.

The pairing orientation is

  B_M(x,y) = <x, M y>,

matching the shell coupling used by the zero-shift Schur layer.  The parity
compression is removed inside the pairing by orthogonal-projection geometry.

Firewalls:
* the archimedean scalar identity correction is retained in the channel matrix;
* no pairing sign, Cauchy--Schwarz certificate, or positivity theorem is
  asserted;
* no zero-shift inverse or pseudoinverse is introduced;
* no branch exclusion, finite-to-infinite closure, or RH theorem is claimed.
-/

/-- Complex sesquilinear pairing generated by a finite matrix. -/
def matrixSesquilinearPairing
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (M : Matrix ι ι ℂ)
    (x y : EuclideanSpace ℂ ι) : ℂ :=
  inner ℂ x (M.toEuclideanLin y)

/-- Identity-matrix acceptance test for the pairing orientation. -/
theorem matrixSesquilinearPairing_one
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (x y : EuclideanSpace ℂ ι) :
    matrixSesquilinearPairing (1 : Matrix ι ι ℂ) x y = inner ℂ x y := by
  unfold matrixSesquilinearPairing
  have hone :
      (1 : Matrix ι ι ℂ).toEuclideanLin y = y := by
    change (Matrix.toLpLin 2 2 (1 : Matrix ι ι ℂ)) y = y
    rw [Matrix.toLpLin_one]
    rfl
  rw [hone]

/-- Exact production channel matrix used for off-diagonal pairing.  This is the
#136 energy decomposition before taking a diagonal real part. -/
def canonicalSourceChannelMatrix
    (L : ℝ) (K : ℕ) :
    Matrix (Fin (2 * K + 1)) (Fin (2 * K + 1)) ℂ :=
  canonicalPoleMatrix L K -
    reducedCanonicalArchDiagonalMatrix L K -
    reducedCanonicalArchOffDiagonalMatrix L K -
    ((canonicalArchScalarCorrection L : ℝ) : ℂ) •
      (1 : Matrix (Fin (2 * K + 1)) (Fin (2 * K + 1)) ℂ) -
    ∑ q ∈ Finset.Icc 2 ⌊Real.exp L⌋₊,
      primeSourceWeight q • sourceMatrix (primeSourceCoordinate q L) K

/-- The production canonical matrix is exactly the explicit channel matrix.
No scalar correction is dropped. -/
theorem canonicalSourceMatrix_eq_channelMatrix
    {L : ℝ} (hL : 0 < L) (K : ℕ) :
    canonicalSourceMatrix L K = canonicalSourceChannelMatrix L K := by
  unfold canonicalSourceChannelMatrix
  rw [canonicalSourceMatrix_eq_pole_sub_arch_sub_prime]
  rw [canonicalArchMatrix_eq_reducedCanonicalArchMatrix_add_scalar hL K]
  rw [reducedCanonicalArchMatrix_eq_diagonal_add_offDiagonal]
  rw [canonicalPrimeMatrix_eq_sum_sourceMatrix]
  abel

/-- Exact complex production-channel pairing. -/
def canonicalSourceChannelPairing
    (L : ℝ) (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1))) : ℂ :=
  matrixSesquilinearPairing (canonicalSourceChannelMatrix L K) x y

/-- Ambient canonical pairing equals the exact production-channel pairing. -/
theorem matrixSesquilinearPairing_canonicalSourceMatrix_eq_channels
    {L : ℝ} (hL : 0 < L) (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1))) :
    matrixSesquilinearPairing (canonicalSourceMatrix L K) x y =
      canonicalSourceChannelPairing L K x y := by
  rw [canonicalSourceMatrix_eq_channelMatrix hL K]
  rfl

/-- Pairing induced by the parity-compressed canonical operator. -/
def parityCanonicalSourcePairing
    (p : ReversalParity) (L : ℝ) (K : ℕ)
    (x y : euclideanParityBoundaryFlatSubspace p K) : ℂ :=
  inner ℂ x (parityCompressedCanonical p L K y)

/-- Orthogonal parity compression does not change a pairing when the first
vector already lies in the parity carrier. -/
theorem parityCanonicalSourcePairing_eq_matrixSesquilinearPairing
    (p : ReversalParity) (L : ℝ) (K : ℕ)
    (x y : euclideanParityBoundaryFlatSubspace p K) :
    parityCanonicalSourcePairing p L K x y =
      matrixSesquilinearPairing (canonicalSourceMatrix L K)
        (x : EuclideanSpace ℂ (Fin (2 * K + 1)))
        (y : EuclideanSpace ℂ (Fin (2 * K + 1))) := by
  unfold parityCanonicalSourcePairing matrixSesquilinearPairing
  change
    inner ℂ
      (x : EuclideanSpace ℂ (Fin (2 * K + 1)))
      ((euclideanParityBoundaryFlatSubspace p K).orthogonalProjectionOnto
        ((canonicalSourceMatrix L K).toEuclideanLin
          (y : EuclideanSpace ℂ (Fin (2 * K + 1))))) =
    inner ℂ
      (x : EuclideanSpace ℂ (Fin (2 * K + 1)))
      ((canonicalSourceMatrix L K).toEuclideanLin
        (y : EuclideanSpace ℂ (Fin (2 * K + 1))) )
  exact Submodule.inner_orthogonalProjectionOnto_eq_of_mem_left
    (K := euclideanParityBoundaryFlatSubspace p K) x _

/-- Headline off-diagonal production identity on one parity carrier. -/
theorem parityCanonicalSourcePairing_eq_channels
    (p : ReversalParity)
    {L : ℝ} (hL : 0 < L) (K : ℕ)
    (x y : euclideanParityBoundaryFlatSubspace p K) :
    parityCanonicalSourcePairing p L K x y =
      canonicalSourceChannelPairing L K
        (x : EuclideanSpace ℂ (Fin (2 * K + 1)))
        (y : EuclideanSpace ℂ (Fin (2 * K + 1))) := by
  rw [parityCanonicalSourcePairing_eq_matrixSesquilinearPairing]
  exact matrixSesquilinearPairing_canonicalSourceMatrix_eq_channels
    hL K
      (x : EuclideanSpace ℂ (Fin (2 * K + 1)))
      (y : EuclideanSpace ℂ (Fin (2 * K + 1)))

end Zeta23.CCM

#print axioms Zeta23.CCM.canonicalSourceMatrix_eq_channelMatrix
#print axioms Zeta23.CCM.parityCanonicalSourcePairing_eq_matrixSesquilinearPairing
#print axioms Zeta23.CCM.parityCanonicalSourcePairing_eq_channels
