import Zeta23.CCM.DictionaryResidualSecondOrderGluing
import Zeta23.CCM.DictionaryTentZeroSummability
import Zeta23.CCM.DictionaryTentMollifierSupport
import Zeta23.CCM.DictionaryTentEFExtension
import Zeta23.CCM.DictionaryZeroSideBridge
import Zeta23.CCM.DictionaryKernelEFExtension
import Zeta23.CCM.DictionaryZeroSideDisplacement
import Zeta23.CCM.RawKernelZeroSideBridge
import Zeta23.CCM.CutoffFreeMatrix
import Zeta23.CCM.LocalizedBasis
import Zeta23.CCM.LocalizedFiniteSpace
import Zeta23.CCM.BoundaryFlatFiniteSpace
import Zeta23.CCM.LocalizedFourierApproximation
import Zeta23.CCM.BoundaryFlatProjection
import Zeta23.CCM.BoundaryFlatApproximation
import Zeta23.CCM.LocalizedWeilRestriction
import Zeta23.CCM.SourceWeilMatrixReconciliation
import Zeta23.CCM.SourceNormalizationRepair
import Zeta23.CCM.ConstrainedCanonicalSector
import Zeta23.CCM.ConstrainedEuclideanSector
import Zeta23.CCM.NestedFinite
import Zeta23.CCM.ConstrainedParity
import Zeta23.CCM.ConstrainedParityGeometry
import Zeta23.CCM.ParityBadness
import Zeta23.CCM.ConstrainedParitySpectrum
import Zeta23.CCM.FirstBadRigidity
import Zeta23.CCM.ParityNormalSpace
import Zeta23.CCM.ParityCompressionRankOne
import Zeta23.CCM.SourceKappa
import Zeta23.CCM.DictionaryRHSIdentity
import Zeta23.ExceptionalZero.DisplacementTransfer
import Zeta23.ExceptionalZero.WeilLiteratureBridge
import Zeta23.ExceptionalZero.WeilContinuity
import Zeta23.ExceptionalZero.TwoTranslateContraction
import Zeta23.ExceptionalZero.NegativeWeilTestSupport
import Zeta23.ExceptionalZero.WeilZeroSideEvenization
import Zeta23.ExceptionalZero.BoundaryFlatFiniteWeil
import Zeta23.ExceptionalZero.FiniteNegativeObstruction
import Zeta23.ExceptionalZero.ConstrainedFiniteObstruction
import Zeta23.ExceptionalZero.EuclideanConstrainedObstruction
import Zeta23.ExceptionalZero.NestedEuclideanObstruction
import Zeta23.ExceptionalZero.ParityFirstBadObstruction
import Zeta23.ExceptionalZero.FirstBadParitySpectrum
import Zeta23.ExceptionalZero.FirstBadRigidity

/-!
R003 promoted-claim completeness is machine-checked by research/RHRC/tools/promoted_binding_lint.py against research/RHRC/R003_PROMOTED_BINDINGS.json and CLAIM_REGISTRY.json. Supporting #check declarations may exist without registry promotion; every PROVED_UNCONDITIONAL R003 registry theorem must have both #check and #print axioms here.

# Promoted CCM / R002 / R003 theorem bindings

This module pins promoted RHRC claim IDs to concrete Lean theorem names so that
`lake build Zeta23.CCM` checks the promoted theorem surface transitively.
-/

#check Zeta23.CCM.dictionaryResidualTest_admissible
#print axioms Zeta23.CCM.dictionaryResidualTest_admissible
#check Zeta23.CCM.dictionaryTent_analytic_package
#print axioms Zeta23.CCM.dictionaryTent_analytic_package
#check Zeta23.CCM.dictionaryTent_mollifier_architecture_package
#print axioms Zeta23.CCM.dictionaryTent_mollifier_architecture_package
#check Zeta23.CCM.dictionaryTent_zero_sum_eq_literatureRHS
#print axioms Zeta23.CCM.dictionaryTent_zero_sum_eq_literatureRHS
#check Zeta23.CCM.dictionaryTent_explicitFormula
#print axioms Zeta23.CCM.dictionaryTent_explicitFormula
#check Zeta23.CCM.dictionaryTentDefect_eq_zero
#print axioms Zeta23.CCM.dictionaryTentDefect_eq_zero
#check Zeta23.CCM.zeroSideMatrix_eq_dictionaryMatrix
#print axioms Zeta23.CCM.zeroSideMatrix_eq_dictionaryMatrix
#check Zeta23.CCM.zeroSideMatrix_eq_finiteMatrix_add_correction
#print axioms Zeta23.CCM.zeroSideMatrix_eq_finiteMatrix_add_correction
#check Zeta23.CCM.literatureRHS_dictionaryTest_eq_quadraticForm
#print axioms Zeta23.CCM.literatureRHS_dictionaryTest_eq_quadraticForm
#check Zeta23.CCM.dictionaryTransform_zero_sum_eq_quadraticForm_zeroSideMatrix
#print axioms Zeta23.CCM.dictionaryTransform_zero_sum_eq_quadraticForm_zeroSideMatrix
#check Zeta23.CCM.dictionaryTransform_zero_sum_eq_literatureRHS
#print axioms Zeta23.CCM.dictionaryTransform_zero_sum_eq_literatureRHS
#check Zeta23.CCM.dictionaryTransform_explicitFormula
#print axioms Zeta23.CCM.dictionaryTransform_explicitFormula
#check Zeta23.ExceptionalZero.rank_displacement_le_two_of_eq_smul_add_scalar
#print axioms Zeta23.ExceptionalZero.rank_displacement_le_two_of_eq_smul_add_scalar
#check Zeta23.CCM.zeroSideMatrix_displacement
#print axioms Zeta23.CCM.zeroSideMatrix_displacement
#check Zeta23.CCM.rank_zeroSideMatrix_displacement_le_two
#print axioms Zeta23.CCM.rank_zeroSideMatrix_displacement_le_two


#check Zeta23.CCM.cutoffFreeMatrix_eq_dictionaryMatrix
#print axioms Zeta23.CCM.cutoffFreeMatrix_eq_dictionaryMatrix
#check Zeta23.CCM.cutoffFreeMatrix_eq_finiteMatrix_add_correction
#print axioms Zeta23.CCM.cutoffFreeMatrix_eq_finiteMatrix_add_correction
#check Zeta23.CCM.cutoffFreeMatrixOfCutoff_sq_eq_of_pos
#print axioms Zeta23.CCM.cutoffFreeMatrixOfCutoff_sq_eq_of_pos
#check Zeta23.CCM.zeroSideMatrix_eq_cutoffFreeMatrix
#print axioms Zeta23.CCM.zeroSideMatrix_eq_cutoffFreeMatrix

#check Zeta23.CCM.rawKernel_zero_entry_summable
#print axioms Zeta23.CCM.rawKernel_zero_entry_summable
#check Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_smul_zeroSideMatrix
#print axioms Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_smul_zeroSideMatrix
#check Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_finiteMatrix_add_four_correction
#print axioms Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_finiteMatrix_add_four_correction
#check Zeta23.CCM.rawKernelZeroSideMatrix_displacement
#print axioms Zeta23.CCM.rawKernelZeroSideMatrix_displacement
#check Zeta23.CCM.rank_rawKernelZeroSideMatrix_displacement_le_two
#print axioms Zeta23.CCM.rank_rawKernelZeroSideMatrix_displacement_le_two


#check Zeta23.CCM.hardWindowCharacterCorrelation_eq_qBasis
#print axioms Zeta23.CCM.hardWindowCharacterCorrelation_eq_qBasis
#check Zeta23.CCM.hardWindowCharacterCorrelation_centered_eq_qBasis
#print axioms Zeta23.CCM.hardWindowCharacterCorrelation_centered_eq_qBasis
#check Zeta23.CCM.two_mul_dictionaryBasisTest_eq_kernel
#print axioms Zeta23.CCM.two_mul_dictionaryBasisTest_eq_kernel


#check Zeta23.CCM.localizedFiniteVector_eq_indicator
#print axioms Zeta23.CCM.localizedFiniteVector_eq_indicator
#check Zeta23.CCM.localizedFiniteVector_memLp_two
#print axioms Zeta23.CCM.localizedFiniteVector_memLp_two
#check Zeta23.CCM.localizedWeilCorrelation_basis_eq_qBasis
#print axioms Zeta23.CCM.localizedWeilCorrelation_basis_eq_qBasis
#check Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_basis_sum
#print axioms Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_basis_sum
#check Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_two_mul_dictionaryTest
#print axioms Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_two_mul_dictionaryTest
#check Zeta23.CCM.localizedWeilCorrelation_finiteVector_zero
#print axioms Zeta23.CCM.localizedWeilCorrelation_finiteVector_zero


#check Zeta23.CCM.localizedWeilHalfTest_finiteVector_eq_dictionaryTest
#print axioms Zeta23.CCM.localizedWeilHalfTest_finiteVector_eq_dictionaryTest
#check Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_dictionaryQuadraticForm
#print axioms Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_dictionaryQuadraticForm
#check Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm
#print axioms Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm
#check Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm_ofLambda
#print axioms Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm_ofLambda
#check Zeta23.CCM.finiteRestriction_eq_cutoffFreeQuadraticForm_of_matches
#print axioms Zeta23.CCM.finiteRestriction_eq_cutoffFreeQuadraticForm_of_matches




#check Zeta23.CCM.sourceEq44GammaL_eq_cutoffFreeGammaL
#print axioms Zeta23.CCM.sourceEq44GammaL_eq_cutoffFreeGammaL
#check Zeta23.CCM.sourceEq44ArchComponent_eq_cutoffFreeArchComponent
#print axioms Zeta23.CCM.sourceEq44ArchComponent_eq_cutoffFreeArchComponent
#check Zeta23.CCM.sourceEq44Entry_eq_cutoffFreeEntry
#print axioms Zeta23.CCM.sourceEq44Entry_eq_cutoffFreeEntry
#check Zeta23.CCM.sourceEq44Matrix_eq_cutoffFreeMatrix
#print axioms Zeta23.CCM.sourceEq44Matrix_eq_cutoffFreeMatrix

#check Zeta23.CCM.sourceEq411_integrand_decomposition
#print axioms Zeta23.CCM.sourceEq411_integrand_decomposition
#check Zeta23.CCM.sourceEq411DerivedCorrectionIntegrand_eq_exp_mul_cCorrectionIntegrand
#print axioms Zeta23.CCM.sourceEq411DerivedCorrectionIntegrand_eq_exp_mul_cCorrectionIntegrand
#check Zeta23.CCM.sourceEq411LhsGammaL_eq_cutoffFreeGammaL
#print axioms Zeta23.CCM.sourceEq411LhsGammaL_eq_cutoffFreeGammaL
#check Zeta23.CCM.gammaL_eq_sourceEq411LhsGammaL_add_correction
#print axioms Zeta23.CCM.gammaL_eq_sourceEq411LhsGammaL_add_correction
#check Zeta23.CCM.sourceEq411LhsArchComponent_eq_cutoffFreeArchComponent
#print axioms Zeta23.CCM.sourceEq411LhsArchComponent_eq_cutoffFreeArchComponent
#check Zeta23.CCM.sourceEq411LhsEntry_eq_cutoffFreeEntry
#print axioms Zeta23.CCM.sourceEq411LhsEntry_eq_cutoffFreeEntry
#check Zeta23.CCM.sourceEq411LhsMatrix_eq_cutoffFreeMatrix
#print axioms Zeta23.CCM.sourceEq411LhsMatrix_eq_cutoffFreeMatrix


#check Zeta23.CCM.sourceEq411_corrected_integrated_rewrite
#print axioms Zeta23.CCM.sourceEq411_corrected_integrated_rewrite
#check Zeta23.CCM.canonicalSourceGammaL_eq_rhs_add_derivedCorrection
#print axioms Zeta23.CCM.canonicalSourceGammaL_eq_rhs_add_derivedCorrection
#check Zeta23.CCM.canonicalSourceMatrix_eq_sourceEq44Matrix
#print axioms Zeta23.CCM.canonicalSourceMatrix_eq_sourceEq44Matrix
#check Zeta23.CCM.canonicalSourceMatrix_eq_dictionaryMatrix
#print axioms Zeta23.CCM.canonicalSourceMatrix_eq_dictionaryMatrix
#check Zeta23.CCM.canonicalSourceMatrix_eq_legacyPrintedMatrix_add_correction
#print axioms Zeta23.CCM.canonicalSourceMatrix_eq_legacyPrintedMatrix_add_correction
#check Zeta23.CCM.canonicalSourceMatrix_displacement
#print axioms Zeta23.CCM.canonicalSourceMatrix_displacement
#check Zeta23.CCM.rank_canonicalSourceMatrix_displacement_le_two
#print axioms Zeta23.CCM.rank_canonicalSourceMatrix_displacement_le_two


#check Zeta23.CCM.sourceLength_pos
#print axioms Zeta23.CCM.sourceLength_pos
#check Zeta23.CCM.sourceLogCoordinate_inv
#print axioms Zeta23.CCM.sourceLogCoordinate_inv
#check Zeta23.CCM.sourceLogCoordinate_self
#print axioms Zeta23.CCM.sourceLogCoordinate_self
#check Zeta23.CCM.sourceLogCoordinate_mem_Icc
#print axioms Zeta23.CCM.sourceLogCoordinate_mem_Icc
#check Zeta23.CCM.sourceLogCoordinate_sourceExpCoordinate
#print axioms Zeta23.CCM.sourceLogCoordinate_sourceExpCoordinate
#check Zeta23.CCM.sourceExpCoordinate_sourceLogCoordinate
#print axioms Zeta23.CCM.sourceExpCoordinate_sourceLogCoordinate
#check Zeta23.CCM.sourceExpCoordinate_mem_Icc
#print axioms Zeta23.CCM.sourceExpCoordinate_mem_Icc
#check Zeta23.CCM.contDiff_localizedMode
#print axioms Zeta23.CCM.contDiff_localizedMode
#check Zeta23.CCM.contDiff_localizedFiniteFunction
#print axioms Zeta23.CCM.contDiff_localizedFiniteFunction
#check Zeta23.CCM.sourceKappa_localizedMode_eq_sourceMultiplicativeMode
#print axioms Zeta23.CCM.sourceKappa_localizedMode_eq_sourceMultiplicativeMode
#check Zeta23.CCM.sourceKappa_localizedFiniteFunction_eq_sourceFiniteFourierFunction
#print axioms Zeta23.CCM.sourceKappa_localizedFiniteFunction_eq_sourceFiniteFourierFunction
#check Zeta23.CCM.sourceFiniteVector_eq_sum_zeroExtendedModes
#print axioms Zeta23.CCM.sourceFiniteVector_eq_sum_zeroExtendedModes
#check Zeta23.CCM.sourceFiniteVector_support_subset
#print axioms Zeta23.CCM.sourceFiniteVector_support_subset
#check Zeta23.CCM.sourceFiniteVector_hasCompactSupport
#print axioms Zeta23.CCM.sourceFiniteVector_hasCompactSupport
#check Zeta23.CCM.sourceKappaFiniteVector_eq_sourceFiniteVector
#print axioms Zeta23.CCM.sourceKappaFiniteVector_eq_sourceFiniteVector
#check Zeta23.CCM.sourceKappa_localizedFiniteFunction_isSourceFiniteFourierVector
#print axioms Zeta23.CCM.sourceKappa_localizedFiniteFunction_isSourceFiniteFourierVector


#check Zeta23.ExceptionalZero.zeta_invSqZeroWeight_summable
#print axioms Zeta23.ExceptionalZero.zeta_invSqZeroWeight_summable
#check Zeta23.ExceptionalZero.norm_zeta_Wsummand_le_commonSupport
#print axioms Zeta23.ExceptionalZero.norm_zeta_Wsummand_le_commonSupport
#check Zeta23.ExceptionalZero.zeta_W_norm_le_commonSupport
#print axioms Zeta23.ExceptionalZero.zeta_W_norm_le_commonSupport
#check Zeta23.ExceptionalZero.zeta_W_self_sub_self_eq_cross
#print axioms Zeta23.ExceptionalZero.zeta_W_self_sub_self_eq_cross
#check Zeta23.ExceptionalZero.zeta_W_self_sub_self_norm_le_commonSupport
#print axioms Zeta23.ExceptionalZero.zeta_W_self_sub_self_norm_le_commonSupport


#check Zeta23.ExceptionalZero.W_literatureRHS_package_of_lit
#print axioms Zeta23.ExceptionalZero.W_literatureRHS_package_of_lit
#check Zeta23.ExceptionalZero.zeta_W_literatureRHS_package
#print axioms Zeta23.ExceptionalZero.zeta_W_literatureRHS_package
#check Zeta23.ExceptionalZero.zeta_W_eq_literatureRHS_weilTest
#print axioms Zeta23.ExceptionalZero.zeta_W_eq_literatureRHS_weilTest
#check Zeta23.ExceptionalZero.zeta_W_self_eq_literatureRHS_weilTest
#print axioms Zeta23.ExceptionalZero.zeta_W_self_eq_literatureRHS_weilTest


#check Zeta23.ExceptionalZero.zeta_W_twoTranslateCombination_eq_matrixQuadratic
#print axioms Zeta23.ExceptionalZero.zeta_W_twoTranslateCombination_eq_matrixQuadratic
#check Zeta23.ExceptionalZero.exists_poleNeutral_negativeWeilTest_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_poleNeutral_negativeWeilTest_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_negativeWeilTest_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_negativeWeilTest_of_offLine_zero


#check Zeta23.ExceptionalZero.tsupport_translateRight
#print axioms Zeta23.ExceptionalZero.tsupport_translateRight
#check Zeta23.ExceptionalZero.exists_translateRight_strict_aperture
#print axioms Zeta23.ExceptionalZero.exists_translateRight_strict_aperture
#check Zeta23.ExceptionalZero.exists_strictAperture_poleNeutral_negativeWeilTest_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_strictAperture_poleNeutral_negativeWeilTest_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_strictAperture_negativeWeilTest_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_strictAperture_negativeWeilTest_of_offLine_zero


#check Zeta23.zeta_conj_zero
#print axioms Zeta23.zeta_conj_zero
#check Zeta23.zeta_one_sub_zero
#print axioms Zeta23.zeta_one_sub_zero
#check Zeta23.zeta_mult_one_sub
#print axioms Zeta23.zeta_mult_one_sub
#check Zeta23.ExceptionalZero.zetaOneSubEquiv
#check Zeta23.ExceptionalZero.gammaOf_one_sub
#print axioms Zeta23.ExceptionalZero.gammaOf_one_sub
#check Zeta23.ExceptionalZero.paperFT_zeroSideReflectTest
#print axioms Zeta23.ExceptionalZero.paperFT_zeroSideReflectTest
#check Zeta23.ExceptionalZero.zeta_literatureRHS_halfEven_eq
#print axioms Zeta23.ExceptionalZero.zeta_literatureRHS_halfEven_eq
#check Zeta23.ExceptionalZero.zeta_W_self_eq_localizedWeilAdditiveRHS
#print axioms Zeta23.ExceptionalZero.zeta_W_self_eq_localizedWeilAdditiveRHS
#check Zeta23.ExceptionalZero.exists_strictAperture_poleNeutral_negativeLocalizedWeilAdditiveRHS_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_strictAperture_poleNeutral_negativeLocalizedWeilAdditiveRHS_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_strictAperture_negativeLocalizedWeilAdditiveRHS_of_exists_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_strictAperture_negativeLocalizedWeilAdditiveRHS_of_exists_offLine_zero


#check Zeta23.CCM.BoundaryFlatCoefficients
#check Zeta23.CCM.boundaryFlatProject_boundaryFlat
#print axioms Zeta23.CCM.boundaryFlatProject_boundaryFlat
#check Zeta23.CCM.boundaryFlatProject_eq_self_of_boundaryFlat
#print axioms Zeta23.CCM.boundaryFlatProject_eq_self_of_boundaryFlat
#check Zeta23.CCM.boundaryFlatProject_idempotent
#print axioms Zeta23.CCM.boundaryFlatProject_idempotent
#check Zeta23.CCM.localizedFiniteFunction_zero_eq_centeredMoment_zero
#print axioms Zeta23.CCM.localizedFiniteFunction_zero_eq_centeredMoment_zero
#check Zeta23.CCM.localizedFiniteFirstJet_zero_eq_centeredMoment_one
#print axioms Zeta23.CCM.localizedFiniteFirstJet_zero_eq_centeredMoment_one
#check Zeta23.CCM.localizedFiniteSecondJet_zero_eq_centeredMoment_two
#print axioms Zeta23.CCM.localizedFiniteSecondJet_zero_eq_centeredMoment_two
#check Zeta23.CCM.contDiff_localizedFiniteVector_of_boundaryFlat
#print axioms Zeta23.CCM.contDiff_localizedFiniteVector_of_boundaryFlat
#check Zeta23.CCM.boundaryKillerCoefficients_boundaryFlat
#print axioms Zeta23.CCM.boundaryKillerCoefficients_boundaryFlat
#check Zeta23.CCM.boundaryKillerCoefficients_ne_zero
#print axioms Zeta23.CCM.boundaryKillerCoefficients_ne_zero
#check Zeta23.ExceptionalZero.zeta_W_boundaryFlatFiniteVector_eq_cutoffFreeQuadraticForm
#print axioms Zeta23.ExceptionalZero.zeta_W_boundaryFlatFiniteVector_eq_cutoffFreeQuadraticForm
#check Zeta23.ExceptionalZero.zeta_W_boundaryFlatFiniteVector_eq_canonicalSourceQuadraticForm
#print axioms Zeta23.ExceptionalZero.zeta_W_boundaryFlatFiniteVector_eq_canonicalSourceQuadraticForm


#check Zeta23.CCM.strictSupport_endpoint_jet_package
#print axioms Zeta23.CCM.strictSupport_endpoint_jet_package
#check Zeta23.CCM.localizedMode_eq_addCircle_fourier
#print axioms Zeta23.CCM.localizedMode_eq_addCircle_fourier
#check Zeta23.CCM.localizedFrequency_ne_zero
#print axioms Zeta23.CCM.localizedFrequency_ne_zero
#check Zeta23.CCM.exists_centeredIndex_eq_of_bounds
#print axioms Zeta23.CCM.exists_centeredIndex_eq_of_bounds
#check Zeta23.CCM.exists_support_natAbs_bound
#print axioms Zeta23.CCM.exists_support_natAbs_bound


#check Zeta23.CCM.addCircleFourierPolynomial_apply
#print axioms Zeta23.CCM.addCircleFourierPolynomial_apply
#check Zeta23.CCM.fourierCoeff_addCircleFourierPolynomial
#print axioms Zeta23.CCM.fourierCoeff_addCircleFourierPolynomial
#check Zeta23.CCM.periodicSecondDerivMap_fourierCoeff_zero
#print axioms Zeta23.CCM.periodicSecondDerivMap_fourierCoeff_zero
#check Zeta23.CCM.exists_zeroModeFree_secondDeriv_fourierPolynomial
#print axioms Zeta23.CCM.exists_zeroModeFree_secondDeriv_fourierPolynomial
#check Zeta23.CCM.localizedFiniteFunction_centeredCoefficientsOfFinsupp_eq
#print axioms Zeta23.CCM.localizedFiniteFunction_centeredCoefficientsOfFinsupp_eq
#check Zeta23.CCM.localizedFiniteSecondJet_twicePrimitive_eq
#print axioms Zeta23.CCM.localizedFiniteSecondJet_twicePrimitive_eq
#check Zeta23.CCM.firstJet_error_norm_le_of_secondJet_error
#print axioms Zeta23.CCM.firstJet_error_norm_le_of_secondJet_error
#check Zeta23.CCM.function_error_norm_le_of_firstJet_error
#print axioms Zeta23.CCM.function_error_norm_le_of_firstJet_error
#check Zeta23.CCM.exists_localizedFinite_uniform_C2_approx
#print axioms Zeta23.CCM.exists_localizedFinite_uniform_C2_approx


#check Zeta23.CCM.centeredMoment_zero_eq_zero_of_localizedFiniteFunction_zero
#print axioms Zeta23.CCM.centeredMoment_zero_eq_zero_of_localizedFiniteFunction_zero
#check Zeta23.CCM.deriv_deriv_localizedFiniteVector_eq_indicator_secondJet
#print axioms Zeta23.CCM.deriv_deriv_localizedFiniteVector_eq_indicator_secondJet
#check Zeta23.CCM.exists_boundaryFlatFinite_WCONT_approx
#print axioms Zeta23.CCM.exists_boundaryFlatFinite_WCONT_approx


#check Zeta23.ExceptionalZero.integral_norm_le_integral_norm_sub_add
#print axioms Zeta23.ExceptionalZero.integral_norm_le_integral_norm_sub_add
#check Zeta23.ExceptionalZero.zeta_W_self_sub_self_norm_le_of_WCONT_errors
#print axioms Zeta23.ExceptionalZero.zeta_W_self_sub_self_norm_le_of_WCONT_errors
#check Zeta23.ExceptionalZero.exists_boundaryFlatFinite_negativeW_of_strictAperture
#print axioms Zeta23.ExceptionalZero.exists_boundaryFlatFinite_negativeW_of_strictAperture
#check Zeta23.ExceptionalZero.exists_boundaryFlat_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_boundaryFlat_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_boundaryFlat_negativeCanonicalSourceQuadraticForm_of_exists_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_boundaryFlat_negativeCanonicalSourceQuadraticForm_of_exists_offLine_zero

#check Zeta23.CCM.centeredMomentLinearMap_apply
#print axioms Zeta23.CCM.centeredMomentLinearMap_apply
#check Zeta23.CCM.mem_boundaryFlatSubspace_iff
#print axioms Zeta23.CCM.mem_boundaryFlatSubspace_iff
#check Zeta23.CCM.indexMatrix_mulVec_apply
#print axioms Zeta23.CCM.indexMatrix_mulVec_apply
#check Zeta23.CCM.centeredMoment_indexMatrix_mulVec
#print axioms Zeta23.CCM.centeredMoment_indexMatrix_mulVec
#check Zeta23.CCM.boundaryFlat_moment_flag
#print axioms Zeta23.CCM.boundaryFlat_moment_flag
#check Zeta23.CCM.canonicalSourceMatrix_conjTranspose
#print axioms Zeta23.CCM.canonicalSourceMatrix_conjTranspose
#check Zeta23.CCM.canonicalSourceMatrix_isHermitian
#print axioms Zeta23.CCM.canonicalSourceMatrix_isHermitian
#check Zeta23.CCM.canonicalSourceMatrix_displacement_mulVec_of_moment_zero
#print axioms Zeta23.CCM.canonicalSourceMatrix_displacement_mulVec_of_moment_zero
#check Zeta23.CCM.boundaryFlat_canonical_displacement_package
#print axioms Zeta23.CCM.boundaryFlat_canonical_displacement_package
#check Zeta23.CCM.quadraticForm_smul
#print axioms Zeta23.CCM.quadraticForm_smul

#check Zeta23.ExceptionalZero.ne_zero_of_quadraticForm_re_neg
#print axioms Zeta23.ExceptionalZero.ne_zero_of_quadraticForm_re_neg
#check Zeta23.ExceptionalZero.exists_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_ne_zero_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_ne_zero_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#check Zeta23.ExceptionalZero.quadraticForm_inv_norm_smul_re_neg
#print axioms Zeta23.ExceptionalZero.quadraticForm_inv_norm_smul_re_neg
#check Zeta23.ExceptionalZero.exists_unit_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_unit_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_unit_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_exists_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_unit_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_exists_offLine_zero



#check Zeta23.CCM.boundaryMomentTripleMap_apply
#print axioms Zeta23.CCM.boundaryMomentTripleMap_apply
#check Zeta23.CCM.ker_boundaryMomentTripleMap
#print axioms Zeta23.CCM.ker_boundaryMomentTripleMap
#check Zeta23.CCM.boundaryMomentTripleMap_surjective
#print axioms Zeta23.CCM.boundaryMomentTripleMap_surjective
#check Zeta23.CCM.finrank_boundaryFlatSubspace
#print axioms Zeta23.CCM.finrank_boundaryFlatSubspace
#check Zeta23.CCM.boundaryFlatSubspace_one_eq_bot
#print axioms Zeta23.CCM.boundaryFlatSubspace_one_eq_bot
#check Zeta23.CCM.two_le_of_ne_zero_mem_boundaryFlatSubspace
#print axioms Zeta23.CCM.two_le_of_ne_zero_mem_boundaryFlatSubspace
#check Zeta23.CCM.mem_euclideanBoundaryFlatSubspace_iff_boundaryFlat
#print axioms Zeta23.CCM.mem_euclideanBoundaryFlatSubspace_iff_boundaryFlat
#check Zeta23.CCM.finrank_euclideanBoundaryFlatSubspace
#print axioms Zeta23.CCM.finrank_euclideanBoundaryFlatSubspace
#check Zeta23.CCM.canonicalSourceMatrix_toEuclideanLin_isSymmetric
#print axioms Zeta23.CCM.canonicalSourceMatrix_toEuclideanLin_isSymmetric
#check Zeta23.CCM.quadraticForm_eq_inner_toEuclideanLin
#print axioms Zeta23.CCM.quadraticForm_eq_inner_toEuclideanLin
#check Zeta23.CCM.quadraticForm_re_eq_re_inner_apply_self
#print axioms Zeta23.CCM.quadraticForm_re_eq_re_inner_apply_self
#check Zeta23.ExceptionalZero.exists_two_le_N_ne_zero_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_two_le_N_ne_zero_mem_boundaryFlatSubspace_negativeCanonicalSourceQuadraticForm_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_exists_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_exists_offLine_zero

#check Zeta23.CCM.centeredIndex_centeredEmbedding
#print axioms Zeta23.CCM.centeredIndex_centeredEmbedding
#check Zeta23.CCM.canonicalSourceMatrix_submatrix_centeredEmbedding
#print axioms Zeta23.CCM.canonicalSourceMatrix_submatrix_centeredEmbedding
#check Zeta23.CCM.centeredMoment_centeredZeroExtend
#print axioms Zeta23.CCM.centeredMoment_centeredZeroExtend
#check Zeta23.CCM.localizedFiniteVector_centeredZeroExtend
#print axioms Zeta23.CCM.localizedFiniteVector_centeredZeroExtend
#check Zeta23.CCM.quadraticForm_canonicalSourceMatrix_centeredZeroExtend
#print axioms Zeta23.CCM.quadraticForm_canonicalSourceMatrix_centeredZeroExtend
#check Zeta23.CCM.euclideanCenteredZeroExtend_mem_euclideanBoundaryFlatSubspace
#print axioms Zeta23.CCM.euclideanCenteredZeroExtend_mem_euclideanBoundaryFlatSubspace
#check Zeta23.CCM.re_inner_canonicalSourceMatrix_euclideanCenteredZeroExtend
#print axioms Zeta23.CCM.re_inner_canonicalSourceMatrix_euclideanCenteredZeroExtend
#check Zeta23.ExceptionalZero.negativeEuclideanConstrained_persists_of_le
#print axioms Zeta23.ExceptionalZero.negativeEuclideanConstrained_persists_of_le
#check Zeta23.ExceptionalZero.exists_fixedAperture_forall_ge_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_fixedAperture_forall_ge_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_fixedAperture_forall_ge_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_exists_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_fixedAperture_forall_ge_ne_zero_mem_euclideanBoundaryFlatSubspace_negativeCanonicalInnerSelf_of_exists_offLine_zero

#check Zeta23.CCM.centeredIndex_rev
#print axioms Zeta23.CCM.centeredIndex_rev
#check Zeta23.CCM.centeredEmbedding_rev
#print axioms Zeta23.CCM.centeredEmbedding_rev
#check Zeta23.CCM.centeredMoment_reverseCoefficients
#print axioms Zeta23.CCM.centeredMoment_reverseCoefficients
#check Zeta23.CCM.canonicalSourceMatrix_apply_rev_rev
#print axioms Zeta23.CCM.canonicalSourceMatrix_apply_rev_rev
#check Zeta23.CCM.displacementVector_rev
#print axioms Zeta23.CCM.displacementVector_rev
#check Zeta23.CCM.canonicalSourceMatrix_mulVec_reverseCoefficients
#print axioms Zeta23.CCM.canonicalSourceMatrix_mulVec_reverseCoefficients
#check Zeta23.CCM.displacementPairing_eq_zero_of_even
#print axioms Zeta23.CCM.displacementPairing_eq_zero_of_even
#check Zeta23.CCM.canonicalSourceMatrix_displacement_mulVec_even_boundaryFlat
#print axioms Zeta23.CCM.canonicalSourceMatrix_displacement_mulVec_even_boundaryFlat

#check Zeta23.CCM.evenBoundaryFlatSubspace_inf_oddBoundaryFlatSubspace
#print axioms Zeta23.CCM.evenBoundaryFlatSubspace_inf_oddBoundaryFlatSubspace
#check Zeta23.CCM.evenBoundaryFlatSubspace_sup_oddBoundaryFlatSubspace
#print axioms Zeta23.CCM.evenBoundaryFlatSubspace_sup_oddBoundaryFlatSubspace
#check Zeta23.CCM.evenToOddIndexLinearMap_injective
#print axioms Zeta23.CCM.evenToOddIndexLinearMap_injective
#check Zeta23.CCM.evenToOddIndexLinearMap_surjective
#print axioms Zeta23.CCM.evenToOddIndexLinearMap_surjective
#check Zeta23.CCM.evenOddBoundaryFlatLinearEquiv
#print axioms Zeta23.CCM.evenOddBoundaryFlatLinearEquiv
#check Zeta23.CCM.finrank_evenBoundaryFlatSubspace
#print axioms Zeta23.CCM.finrank_evenBoundaryFlatSubspace
#check Zeta23.CCM.finrank_oddBoundaryFlatSubspace
#print axioms Zeta23.CCM.finrank_oddBoundaryFlatSubspace
#check Zeta23.CCM.finrank_euclideanEvenBoundaryFlatSubspace
#print axioms Zeta23.CCM.finrank_euclideanEvenBoundaryFlatSubspace
#check Zeta23.CCM.finrank_euclideanOddBoundaryFlatSubspace
#print axioms Zeta23.CCM.finrank_euclideanOddBoundaryFlatSubspace
#check Zeta23.CCM.euclideanCenteredZeroExtend_mem_euclideanEvenBoundaryFlatSubspace
#print axioms Zeta23.CCM.euclideanCenteredZeroExtend_mem_euclideanEvenBoundaryFlatSubspace
#check Zeta23.CCM.euclideanCenteredZeroExtend_mem_euclideanOddBoundaryFlatSubspace
#print axioms Zeta23.CCM.euclideanCenteredZeroExtend_mem_euclideanOddBoundaryFlatSubspace

#check Zeta23.CCM.indexMatrix_mulVec_centeredZeroExtend
#print axioms Zeta23.CCM.indexMatrix_mulVec_centeredZeroExtend
#check Zeta23.CCM.quadraticForm_canonicalSourceMatrix_reverseCoefficients
#print axioms Zeta23.CCM.quadraticForm_canonicalSourceMatrix_reverseCoefficients
#check Zeta23.CCM.quadraticForm_evenPart_add_oddPart
#print axioms Zeta23.CCM.quadraticForm_evenPart_add_oddPart
#check Zeta23.CCM.parityBad_even_or_odd_of_negative
#print axioms Zeta23.CCM.parityBad_even_or_odd_of_negative
#check Zeta23.CCM.two_le_of_parityBad
#print axioms Zeta23.CCM.two_le_of_parityBad
#check Zeta23.CCM.parityBad_persists_of_le
#print axioms Zeta23.CCM.parityBad_persists_of_le
#check Zeta23.CCM.exists_least_parityBad
#print axioms Zeta23.CCM.exists_least_parityBad
#check Zeta23.CCM.nonnegative_of_lt_least_parityBad
#print axioms Zeta23.CCM.nonnegative_of_lt_least_parityBad
#check Zeta23.CCM.euclidean_nonnegative_of_lt_least_parityBad
#print axioms Zeta23.CCM.euclidean_nonnegative_of_lt_least_parityBad
#check Zeta23.CCM.finrank_euclideanParitySuccShell
#print axioms Zeta23.CCM.finrank_euclideanParitySuccShell
#check Zeta23.ExceptionalZero.exists_fixedAperture_parityBad_tail_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_fixedAperture_parityBad_tail_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_leastParityBad_oneDimShell_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_leastParityBad_oneDimShell_of_offLine_zero


#check Zeta23.CCM.parityCompressedCanonical
#check Zeta23.CCM.inner_parityCompressedCanonical_self
#print axioms Zeta23.CCM.inner_parityCompressedCanonical_self
#check Zeta23.CCM.re_inner_parityCompressedCanonical_self
#print axioms Zeta23.CCM.re_inner_parityCompressedCanonical_self
#check Zeta23.CCM.parityCompressedCanonical_isSymmetric
#print axioms Zeta23.CCM.parityCompressedCanonical_isSymmetric
#check Zeta23.CCM.exists_negative_compressed_direction_of_parityBad
#print axioms Zeta23.CCM.exists_negative_compressed_direction_of_parityBad
#check Zeta23.CCM.exists_negative_eigenmode_of_parityBad
#print axioms Zeta23.CCM.exists_negative_eigenmode_of_parityBad
#check Zeta23.CCM.re_inner_successor_nonnegative_on_centeredImage
#print axioms Zeta23.CCM.re_inner_successor_nonnegative_on_centeredImage
#check Zeta23.CCM.negative_eigenmode_not_centeredImage
#print axioms Zeta23.CCM.negative_eigenmode_not_centeredImage
#check Zeta23.ExceptionalZero.exists_firstBadParity_negativeEigenmode_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_firstBadParity_negativeEigenmode_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_firstBadParity_negativeEigenmode_of_exists_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_firstBadParity_negativeEigenmode_of_exists_offLine_zero


#check Zeta23.CCM.paritySuccShellProjection_ne_zero_of_not_embedded
#print axioms Zeta23.CCM.paritySuccShellProjection_ne_zero_of_not_embedded
#check Zeta23.CCM.negative_eigenmode_paritySuccShell_projection_ne_zero
#print axioms Zeta23.CCM.negative_eigenmode_paritySuccShell_projection_ne_zero
#check Zeta23.CCM.re_inner_successor_nonnegative_on_embeddedPredecessor
#print axioms Zeta23.CCM.re_inner_successor_nonnegative_on_embeddedPredecessor
#check Zeta23.CCM.evenBoundaryFlat_normal_eq_evenNormalSubspace
#print axioms Zeta23.CCM.evenBoundaryFlat_normal_eq_evenNormalSubspace
#check Zeta23.CCM.oddBoundaryFlat_normal_eq_oddNormalSubspace
#print axioms Zeta23.CCM.oddBoundaryFlat_normal_eq_oddNormalSubspace
#check Zeta23.CCM.parityKKTResidual_of_eigenmode
#print axioms Zeta23.CCM.parityKKTResidual_of_eigenmode
#check Zeta23.ExceptionalZero.exists_firstBadParity_shell_KKT_of_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_firstBadParity_shell_KKT_of_offLine_zero
#check Zeta23.ExceptionalZero.exists_firstBadParity_shell_KKT_of_exists_offLine_zero
#print axioms Zeta23.ExceptionalZero.exists_firstBadParity_shell_KKT_of_exists_offLine_zero


#check Zeta23.CCM.euclideanEvenOddBoundaryFlatLinearEquiv
#print axioms Zeta23.CCM.euclideanEvenOddBoundaryFlatLinearEquiv
#check Zeta23.CCM.evenCompressionResidual_mem_evenNormalSubspace
#print axioms Zeta23.CCM.evenCompressionResidual_mem_evenNormalSubspace
#check Zeta23.CCM.canonicalSourceMatrix_toEuclideanLin_commutes_index_on_even
#print axioms Zeta23.CCM.canonicalSourceMatrix_toEuclideanLin_commutes_index_on_even
#check Zeta23.CCM.oddCubicCompressionVector_ne_zero
#print axioms Zeta23.CCM.oddCubicCompressionVector_ne_zero
#check Zeta23.CCM.exists_evenOddCompressedIntertwiningDefect_eq_smul_cubic
#print axioms Zeta23.CCM.exists_evenOddCompressedIntertwiningDefect_eq_smul_cubic
#check Zeta23.CCM.range_evenOddCompressedIntertwiningDefect_le
#print axioms Zeta23.CCM.range_evenOddCompressedIntertwiningDefect_le
#check Zeta23.CCM.finrank_range_evenOddCompressedIntertwiningDefect_le_one
#print axioms Zeta23.CCM.finrank_range_evenOddCompressedIntertwiningDefect_le_one
#check Zeta23.CCM.finrank_range_conjugatedParityCompressionDefect_le_one
#print axioms Zeta23.CCM.finrank_range_conjugatedParityCompressionDefect_le_one
