import Zeta23.CCM.DictionaryResidualSecondOrderGluing
import Zeta23.CCM.DictionaryTentZeroSummability
import Zeta23.CCM.DictionaryTentMollifierSupport
import Zeta23.CCM.DictionaryTentEFExtension
import Zeta23.CCM.DictionaryZeroSideBridge
import Zeta23.CCM.DictionaryKernelEFExtension
import Zeta23.CCM.DictionaryZeroSideDisplacement
import Zeta23.CCM.RawKernelZeroSideBridge
import Zeta23.CCM.CutoffFreeMatrix
import Zeta23.CCM.LocalizedBasis
import Zeta23.CCM.LocalizedFiniteSpace
import Zeta23.CCM.LocalizedWeilRestriction
import Zeta23.CCM.SourceWeilMatrixReconciliation
import Zeta23.CCM.SourceNormalizationRepair
import Zeta23.CCM.SourceKappa
import Zeta23.CCM.DictionaryRHSIdentity
import Zeta23.ExceptionalZero.DisplacementTransfer

/-!
# Promoted CCM / R002 / R003 theorem bindings

This module pins promoted RHRC claim IDs to concrete Lean theorem names so that
`lake build Zeta23.CCM` checks the promoted theorem surface transitively.
-/

#check Zeta23.CCM.dictionaryResidualTest_admissible
#check Zeta23.CCM.dictionaryTent_analytic_package
#check Zeta23.CCM.dictionaryTent_mollifier_architecture_package
#print axioms Zeta23.CCM.dictionaryTent_mollifier_architecture_package
#check Zeta23.CCM.dictionaryTent_zero_sum_eq_literatureRHS
#print axioms Zeta23.CCM.dictionaryTent_zero_sum_eq_literatureRHS
#check Zeta23.CCM.dictionaryTent_explicitFormula
#print axioms Zeta23.CCM.dictionaryTent_explicitFormula
#check Zeta23.CCM.dictionaryTentDefect_eq_zero
#print axioms Zeta23.CCM.dictionaryTentDefect_eq_zero
#check Zeta23.CCM.zeroSideMatrix_eq_dictionaryMatrix
#print axioms Zeta23.CCM.zeroSideMatrix_eq_dictionaryMatrix
#check Zeta23.CCM.zeroSideMatrix_eq_finiteMatrix_add_correction
#print axioms Zeta23.CCM.zeroSideMatrix_eq_finiteMatrix_add_correction
#check Zeta23.CCM.literatureRHS_dictionaryTest_eq_quadraticForm
#print axioms Zeta23.CCM.literatureRHS_dictionaryTest_eq_quadraticForm
#check Zeta23.CCM.dictionaryTransform_zero_sum_eq_quadraticForm_zeroSideMatrix
#print axioms Zeta23.CCM.dictionaryTransform_zero_sum_eq_quadraticForm_zeroSideMatrix
#check Zeta23.CCM.dictionaryTransform_zero_sum_eq_literatureRHS
#print axioms Zeta23.CCM.dictionaryTransform_zero_sum_eq_literatureRHS
#check Zeta23.CCM.dictionaryTransform_explicitFormula
#print axioms Zeta23.CCM.dictionaryTransform_explicitFormula
#check Zeta23.ExceptionalZero.rank_displacement_le_two_of_eq_smul_add_scalar
#check Zeta23.CCM.zeroSideMatrix_displacement
#print axioms Zeta23.CCM.zeroSideMatrix_displacement
#check Zeta23.CCM.rank_zeroSideMatrix_displacement_le_two
#print axioms Zeta23.CCM.rank_zeroSideMatrix_displacement_le_two


#check Zeta23.CCM.cutoffFreeMatrix_eq_dictionaryMatrix
#print axioms Zeta23.CCM.cutoffFreeMatrix_eq_dictionaryMatrix
#check Zeta23.CCM.cutoffFreeMatrix_eq_finiteMatrix_add_correction
#print axioms Zeta23.CCM.cutoffFreeMatrix_eq_finiteMatrix_add_correction
#check Zeta23.CCM.cutoffFreeMatrixOfCutoff_sq_eq_of_pos
#print axioms Zeta23.CCM.cutoffFreeMatrixOfCutoff_sq_eq_of_pos
#check Zeta23.CCM.zeroSideMatrix_eq_cutoffFreeMatrix
#print axioms Zeta23.CCM.zeroSideMatrix_eq_cutoffFreeMatrix

#check Zeta23.CCM.rawKernel_zero_entry_summable
#print axioms Zeta23.CCM.rawKernel_zero_entry_summable
#check Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_smul_zeroSideMatrix
#print axioms Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_smul_zeroSideMatrix
#check Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_finiteMatrix_add_four_correction
#print axioms Zeta23.CCM.rawKernelZeroSideMatrix_eq_two_finiteMatrix_add_four_correction
#check Zeta23.CCM.rawKernelZeroSideMatrix_displacement
#print axioms Zeta23.CCM.rawKernelZeroSideMatrix_displacement
#check Zeta23.CCM.rank_rawKernelZeroSideMatrix_displacement_le_two
#print axioms Zeta23.CCM.rank_rawKernelZeroSideMatrix_displacement_le_two


#check Zeta23.CCM.hardWindowCharacterCorrelation_eq_qBasis
#print axioms Zeta23.CCM.hardWindowCharacterCorrelation_eq_qBasis
#check Zeta23.CCM.hardWindowCharacterCorrelation_centered_eq_qBasis
#print axioms Zeta23.CCM.hardWindowCharacterCorrelation_centered_eq_qBasis
#check Zeta23.CCM.two_mul_dictionaryBasisTest_eq_kernel
#print axioms Zeta23.CCM.two_mul_dictionaryBasisTest_eq_kernel


#check Zeta23.CCM.localizedFiniteVector_eq_indicator
#print axioms Zeta23.CCM.localizedFiniteVector_eq_indicator
#check Zeta23.CCM.localizedFiniteVector_memLp_two
#print axioms Zeta23.CCM.localizedFiniteVector_memLp_two
#check Zeta23.CCM.localizedWeilCorrelation_basis_eq_qBasis
#print axioms Zeta23.CCM.localizedWeilCorrelation_basis_eq_qBasis
#check Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_basis_sum
#print axioms Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_basis_sum
#check Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_two_mul_dictionaryTest
#print axioms Zeta23.CCM.localizedWeilCorrelation_finiteVector_eq_two_mul_dictionaryTest
#check Zeta23.CCM.localizedWeilCorrelation_finiteVector_zero
#print axioms Zeta23.CCM.localizedWeilCorrelation_finiteVector_zero


#check Zeta23.CCM.localizedWeilHalfTest_finiteVector_eq_dictionaryTest
#print axioms Zeta23.CCM.localizedWeilHalfTest_finiteVector_eq_dictionaryTest
#check Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_dictionaryQuadraticForm
#print axioms Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_dictionaryQuadraticForm
#check Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm
#print axioms Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm
#check Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm_ofLambda
#print axioms Zeta23.CCM.localizedWeilAdditiveRHS_finiteVector_eq_cutoffFreeQuadraticForm_ofLambda
#check Zeta23.CCM.finiteRestriction_eq_cutoffFreeQuadraticForm_of_matches
#print axioms Zeta23.CCM.finiteRestriction_eq_cutoffFreeQuadraticForm_of_matches




#check Zeta23.CCM.sourceEq44GammaL_eq_cutoffFreeGammaL
#print axioms Zeta23.CCM.sourceEq44GammaL_eq_cutoffFreeGammaL
#check Zeta23.CCM.sourceEq44ArchComponent_eq_cutoffFreeArchComponent
#print axioms Zeta23.CCM.sourceEq44ArchComponent_eq_cutoffFreeArchComponent
#check Zeta23.CCM.sourceEq44Entry_eq_cutoffFreeEntry
#print axioms Zeta23.CCM.sourceEq44Entry_eq_cutoffFreeEntry
#check Zeta23.CCM.sourceEq44Matrix_eq_cutoffFreeMatrix
#print axioms Zeta23.CCM.sourceEq44Matrix_eq_cutoffFreeMatrix

#check Zeta23.CCM.sourceEq411_integrand_decomposition
#print axioms Zeta23.CCM.sourceEq411_integrand_decomposition
#check Zeta23.CCM.sourceEq411DerivedCorrectionIntegrand_eq_exp_mul_cCorrectionIntegrand
#print axioms Zeta23.CCM.sourceEq411DerivedCorrectionIntegrand_eq_exp_mul_cCorrectionIntegrand
#check Zeta23.CCM.sourceEq411LhsGammaL_eq_cutoffFreeGammaL
#print axioms Zeta23.CCM.sourceEq411LhsGammaL_eq_cutoffFreeGammaL
#check Zeta23.CCM.gammaL_eq_sourceEq411LhsGammaL_add_correction
#print axioms Zeta23.CCM.gammaL_eq_sourceEq411LhsGammaL_add_correction
#check Zeta23.CCM.sourceEq411LhsArchComponent_eq_cutoffFreeArchComponent
#print axioms Zeta23.CCM.sourceEq411LhsArchComponent_eq_cutoffFreeArchComponent
#check Zeta23.CCM.sourceEq411LhsEntry_eq_cutoffFreeEntry
#print axioms Zeta23.CCM.sourceEq411LhsEntry_eq_cutoffFreeEntry
#check Zeta23.CCM.sourceEq411LhsMatrix_eq_cutoffFreeMatrix
#print axioms Zeta23.CCM.sourceEq411LhsMatrix_eq_cutoffFreeMatrix


#check Zeta23.CCM.sourceEq411_corrected_integrated_rewrite
#print axioms Zeta23.CCM.sourceEq411_corrected_integrated_rewrite
#check Zeta23.CCM.canonicalSourceGammaL_eq_rhs_add_derivedCorrection
#print axioms Zeta23.CCM.canonicalSourceGammaL_eq_rhs_add_derivedCorrection
#check Zeta23.CCM.canonicalSourceMatrix_eq_sourceEq44Matrix
#print axioms Zeta23.CCM.canonicalSourceMatrix_eq_sourceEq44Matrix
#check Zeta23.CCM.canonicalSourceMatrix_eq_dictionaryMatrix
#print axioms Zeta23.CCM.canonicalSourceMatrix_eq_dictionaryMatrix
#check Zeta23.CCM.canonicalSourceMatrix_eq_legacyPrintedMatrix_add_correction
#print axioms Zeta23.CCM.canonicalSourceMatrix_eq_legacyPrintedMatrix_add_correction
#check Zeta23.CCM.canonicalSourceMatrix_displacement
#print axioms Zeta23.CCM.canonicalSourceMatrix_displacement
#check Zeta23.CCM.rank_canonicalSourceMatrix_displacement_le_two
#print axioms Zeta23.CCM.rank_canonicalSourceMatrix_displacement_le_two


#check Zeta23.CCM.sourceLength_pos
#print axioms Zeta23.CCM.sourceLength_pos
#check Zeta23.CCM.sourceLogCoordinate_inv
#print axioms Zeta23.CCM.sourceLogCoordinate_inv
#check Zeta23.CCM.sourceLogCoordinate_self
#print axioms Zeta23.CCM.sourceLogCoordinate_self
#check Zeta23.CCM.sourceLogCoordinate_mem_Icc
#print axioms Zeta23.CCM.sourceLogCoordinate_mem_Icc
#check Zeta23.CCM.sourceLogCoordinate_sourceExpCoordinate
#print axioms Zeta23.CCM.sourceLogCoordinate_sourceExpCoordinate
#check Zeta23.CCM.sourceExpCoordinate_sourceLogCoordinate
#print axioms Zeta23.CCM.sourceExpCoordinate_sourceLogCoordinate
#check Zeta23.CCM.sourceExpCoordinate_mem_Icc
#print axioms Zeta23.CCM.sourceExpCoordinate_mem_Icc
#check Zeta23.CCM.contDiff_localizedMode
#print axioms Zeta23.CCM.contDiff_localizedMode
#check Zeta23.CCM.contDiff_localizedFiniteFunction
#print axioms Zeta23.CCM.contDiff_localizedFiniteFunction
#check Zeta23.CCM.sourceKappa_localizedMode_eq_sourceMultiplicativeMode
#print axioms Zeta23.CCM.sourceKappa_localizedMode_eq_sourceMultiplicativeMode
#check Zeta23.CCM.sourceKappa_localizedFiniteFunction_eq_sourceFiniteFourierFunction
#print axioms Zeta23.CCM.sourceKappa_localizedFiniteFunction_eq_sourceFiniteFourierFunction
#check Zeta23.CCM.sourceFiniteVector_eq_sum_zeroExtendedModes
#print axioms Zeta23.CCM.sourceFiniteVector_eq_sum_zeroExtendedModes
#check Zeta23.CCM.sourceFiniteVector_support_subset
#print axioms Zeta23.CCM.sourceFiniteVector_support_subset
#check Zeta23.CCM.sourceFiniteVector_hasCompactSupport
#print axioms Zeta23.CCM.sourceFiniteVector_hasCompactSupport
#check Zeta23.CCM.sourceKappaFiniteVector_eq_sourceFiniteVector
#print axioms Zeta23.CCM.sourceKappaFiniteVector_eq_sourceFiniteVector
#check Zeta23.CCM.sourceKappa_localizedFiniteFunction_isSourceFiniteFourierVector
#print axioms Zeta23.CCM.sourceKappa_localizedFiniteFunction_isSourceFiniteFourierVector
