import Zeta23.CCM.FirstCrossingProductionFirstVariation
import Zeta23.CCM.GlobalParityBottomSimplicity
import Zeta23.CCM.RankOneEigenline
import Mathlib.Analysis.InnerProductSpace.Symmetric

noncomputable section

namespace Zeta23.CCM

open Complex Set
open scoped ComplexConjugate

/-!
# Post-#281 strict-even stationary response

At a strict-even zero mode the source functional already proves that the even
zero eigenspace is a single line.  Self-adjointness of the production first
derivative turns stationarity into orthogonality of E'z to that line.  Finite
dimensional self-adjoint range/kernel geometry then constructs the unique
perpendicular response

  E w = -E' z,   <z,w> = 0.

No inverse on an uncertain complement and no arbitrary gauge choice is used.
-/

/-- Native strict-even compression of the contact operator.  The historical
`evenCompressedCanonical` wrapper is definitionally the even branch of the
generic parity compression; this native copy keeps the Hilbert/module instances
identical throughout the response range/kernel argument. -/
def evenResponseContactOperatorCLM
    (L : ℝ) (K : ℕ) :
    euclideanEvenBoundaryFlatSubspace K →L[ℂ]
      euclideanEvenBoundaryFlatSubspace K :=
  let V := euclideanEvenBoundaryFlatSubspace K
  V.orthogonalProjectionOnto.comp
    ((LinearMap.toContinuousLinearMap
        (canonicalSourceMatrix L K).toEuclideanLin).comp
      (V.subtypeL :
        V →L[ℂ] EuclideanSpace ℂ (Fin (2 * K + 1))))

/-- Linear-map form of the native strict-even contact operator. -/
def evenResponseContactOperator
    (L : ℝ) (K : ℕ) :
    euclideanEvenBoundaryFlatSubspace K →ₗ[ℂ]
      euclideanEvenBoundaryFlatSubspace K :=
  (evenResponseContactOperatorCLM L K).toLinearMap

/-- The native strict-even contact operator agrees pointwise with the existing
explicitly typed even compression. -/
@[simp] theorem evenResponseContactOperator_apply
    (L : ℝ) (K : ℕ)
    (x : euclideanEvenBoundaryFlatSubspace K) :
    evenResponseContactOperator L K x =
      evenCompressedCanonical L K x := by
  apply Subtype.ext
  rfl

/-- Native strict-even contact symmetry, proved without transporting typeclass
instances through the generic parity carrier. -/
theorem evenResponseContactOperator_isSymmetric
    (L : ℝ) (K : ℕ) :
    LinearMap.IsSymmetric (𝕜 := ℂ)
      (E := euclideanEvenBoundaryFlatSubspace K)
      (evenResponseContactOperator L K) := by
  intro x y
  change
    inner ℂ
      ((euclideanEvenBoundaryFlatSubspace K).orthogonalProjectionOnto
        ((canonicalSourceMatrix L K).toEuclideanLin
          (x : EuclideanSpace ℂ (Fin (2 * K + 1))))) y =
    inner ℂ x
      ((euclideanEvenBoundaryFlatSubspace K).orthogonalProjectionOnto
        ((canonicalSourceMatrix L K).toEuclideanLin
          (y : EuclideanSpace ℂ (Fin (2 * K + 1)))))
  rw [Submodule.inner_orthogonalProjectionOnto_eq_of_mem_right,
      Submodule.inner_orthogonalProjectionOnto_eq_of_mem_left]
  exact canonicalSourceMatrix_toEuclideanLin_isSymmetric L K
    (x : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (y : EuclideanSpace ℂ (Fin (2 * K + 1)))

/-- The even zero eigenspace is exactly the line generated by any nonzero
strict-even zero eigenvector. -/
theorem strictEven_zeroKernel_is_line
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (x : euclideanEvenBoundaryFlatSubspace K)
    (hx : evenCompressedCanonical L K x = 0) :
    ∃ c : ℂ, c • z = x := by
  have hfaith :
      ∀ y : euclideanEvenBoundaryFlatSubspace K,
        evenCompressedCanonical L K y = (0 : ℂ) • y →
        cubicDefectFunctional L K y = 0 → y = 0 := by
    intro y hy hS
    exact evenEigenmode_eq_zero_of_source_eq_zero_below_odd
      hL K hK 0 hodd y hy hS
  have hz : evenCompressedCanonical L K z = (0 : ℂ) • z := by
    simpa using hzero
  have hx' : evenCompressedCanonical L K x = (0 : ℂ) • x := by
    simpa using hx
  exact eigenmode_eq_smul_of_functional_kernel
    (evenCompressedCanonical L K) (0 : ℂ)
    (cubicDefectFunctional L K) hfaith hz hzne x hx'

/-- Stationarity plus self-adjointness makes the derivative forcing exactly
orthogonal to the zero eigenvector, not merely zero in real part. -/
theorem inner_firstDerivative_zero_of_stationary
    {L : ℝ} (K : ℕ)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hoperator : EvenProductionContactFirstOperatorRealized L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    inner ℂ
      (evenProductionApertureFirst L K z) z = 0 := by
  let a : ℂ :=
    inner ℂ (evenProductionApertureFirst L K z) z
  have hre : a.re = 0 := by
    calc
      a.re = productionContactFirstVariation .even L K z := by
        simpa [a] using (hoperator z).2
      _ = 0 := hstationary
  have hsym := evenProductionApertureFirst_isSymmetric L K
  have him : a.im = 0 := by
    simpa [a] using hsym.im_inner_apply_self z
  change a = 0
  apply Complex.ext
  · simpa using hre
  · simpa using him

/-- The stationary forcing lies in the range of the strict-even contact
operator. -/
theorem neg_firstDerivative_mem_evenRange_of_stationary_strict
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hoperator : EvenProductionContactFirstOperatorRealized L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    -(evenProductionApertureFirst L K z) ∈
      (evenCompressedCanonical L K).range := by
  let E := evenResponseContactOperator L K
  let b := evenProductionApertureFirst L K z
  have hbz : inner ℂ b z = 0 := by
    simpa [b] using
      inner_firstDerivative_zero_of_stationary K z hoperator hstationary
  have hzb : inner ℂ z b = 0 := by
    rw [inner_eq_zero_symm]
    exact hbz
  have hbker :
      b ∈ (E.ker : Submodule ℂ (euclideanEvenBoundaryFlatSubspace K))ᗮ := by
    intro x hx
    have hxNative : E x = 0 := LinearMap.mem_ker.mp hx
    have hx0 : evenCompressedCanonical L K x = 0 := by
      rw [← evenResponseContactOperator_apply]
      simpa [E] using hxNative
    obtain ⟨c, hc⟩ :=
      strictEven_zeroKernel_is_line hL K hK z hzne hzero hodd x hx0
    rw [← hc]
    rw [inner_smul_left]
    simp [hzb]
  have hEsym :
      LinearMap.IsSymmetric (𝕜 := ℂ)
        (E := euclideanEvenBoundaryFlatSubspace K) E := by
    simpa [E] using evenResponseContactOperator_isSymmetric L K
  have hrangeOrth :
      (E.range : Submodule ℂ (euclideanEvenBoundaryFlatSubspace K))ᗮ = E.ker :=
    hEsym.orthogonal_range
  have hrange :
      E.range =
        (E.ker : Submodule ℂ (euclideanEvenBoundaryFlatSubspace K))ᗮ := by
    calc
      E.range = E.rangeᗮᗮ := by
        symm
        exact Submodule.orthogonal_orthogonal
      _ = E.kerᗮ := by rw [hrangeOrth]
  have hmemNative : -b ∈ E.range := by
    rw [hrange]
    exact
      ((E.ker : Submodule ℂ (euclideanEvenBoundaryFlatSubspace K))ᗮ).neg_mem hbker
  obtain ⟨w, hw⟩ := hmemNative
  change ∃ w : euclideanEvenBoundaryFlatSubspace K,
    evenCompressedCanonical L K w =
      -(evenProductionApertureFirst L K z)
  refine ⟨w, ?_⟩
  rw [← evenResponseContactOperator_apply]
  simpa [E, b] using hw

/-- Existence and uniqueness of the normalized/perpendicular stationary
response. -/
theorem existsUnique_stationaryEvenResponse
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hznorm : ‖z‖ = 1)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hoperator : EvenProductionContactFirstOperatorRealized L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    ∃! w : euclideanEvenBoundaryFlatSubspace K,
      inner ℂ z w = 0 ∧
      evenCompressedCanonical L K w =
        -(evenProductionApertureFirst L K z) := by
  let E := evenCompressedCanonical L K
  let b := evenProductionApertureFirst L K z
  have hmem :
      -b ∈ E.range := by
    simpa [E, b] using
      neg_firstDerivative_mem_evenRange_of_stationary_strict
        hL K hK z hzne hzero hodd hoperator hstationary
  obtain ⟨w0, hw0⟩ := hmem
  have hzz : inner ℂ z z = 1 := by
    rw [inner_self_eq_norm_sq_to_K, hznorm]
    norm_num
  have hzzAmbient :
      inner ℂ
        (z : EuclideanSpace ℂ (Fin (2 * K + 1)))
        (z : EuclideanSpace ℂ (Fin (2 * K + 1))) = 1 := by
    simpa using hzz
  let w : euclideanEvenBoundaryFlatSubspace K :=
    w0 - (inner ℂ z w0) • z
  have hwperp : inner ℂ z w = 0 := by
    dsimp [w]
    rw [inner_sub_right, inner_smul_right]
    change
      inner ℂ
          (z : EuclideanSpace ℂ (Fin (2 * K + 1)))
          (w0 : EuclideanSpace ℂ (Fin (2 * K + 1))) -
        inner ℂ
          (z : EuclideanSpace ℂ (Fin (2 * K + 1)))
          (w0 : EuclideanSpace ℂ (Fin (2 * K + 1))) *
        inner ℂ
          (z : EuclideanSpace ℂ (Fin (2 * K + 1)))
          (z : EuclideanSpace ℂ (Fin (2 * K + 1))) = 0
    rw [hzzAmbient]
    ring
  have hwsolve : E w = -b := by
    dsimp [w]
    rw [map_sub, map_smul, hzero, smul_zero, sub_zero]
    exact hw0
  refine ⟨w, ⟨hwperp, by simpa [E, b] using hwsolve⟩, ?_⟩
  intro y hy
  have hdiff : E (y - w) = 0 := by
    have hySolve : E y = -b := by
      simpa [E, b] using hy.2
    calc
      E (y - w) = E y - E w := by rw [map_sub]
      _ = -b - (-b) := by rw [hySolve, hwsolve]
      _ = 0 := sub_self (-b)
  obtain ⟨c, hc⟩ :=
    strictEven_zeroKernel_is_line
      hL K hK z hzne hzero hodd (y - w) hdiff
  have horth : inner ℂ z (y - w) = 0 := by
    rw [inner_sub_right, hy.1, hwperp, sub_self]
  have hcz : inner ℂ z (c • z) = 0 := by
    rw [hc, horth]
  have hczAmbient :
      inner ℂ
        (z : EuclideanSpace ℂ (Fin (2 * K + 1)))
        (c • (z : EuclideanSpace ℂ (Fin (2 * K + 1)))) = 0 := by
    simpa using hcz
  have hc0 : c = 0 := by
    rw [inner_smul_right, hzzAmbient] at hczAmbient
    simpa using hczAmbient
  have hyw : y - w = 0 := by
    rw [← hc, hc0, zero_smul]
  exact sub_eq_zero.mp hyw

/-- Canonical chosen stationary response. -/
noncomputable def stationaryEvenResponse
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hznorm : ‖z‖ = 1)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hoperator : EvenProductionContactFirstOperatorRealized L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    euclideanEvenBoundaryFlatSubspace K :=
  Classical.choose
    (existsUnique_stationaryEvenResponse
      hL K hK z hzne hznorm hzero hodd hoperator hstationary)

theorem stationaryEvenResponse_spec
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hznorm : ‖z‖ = 1)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hoperator : EvenProductionContactFirstOperatorRealized L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    inner ℂ z
        (stationaryEvenResponse hL K hK z hzne hznorm hzero hodd hoperator hstationary) = 0 ∧
      evenCompressedCanonical L K
        (stationaryEvenResponse hL K hK z hzne hznorm hzero hodd hoperator hstationary) =
          -(evenProductionApertureFirst L K z) :=
  (Classical.choose_spec
    (existsUnique_stationaryEvenResponse
      hL K hK z hzne hznorm hzero hodd hoperator hstationary)).1

end Zeta23.CCM

#print axioms Zeta23.CCM.evenResponseContactOperator_isSymmetric
#print axioms Zeta23.CCM.strictEven_zeroKernel_is_line
#print axioms Zeta23.CCM.inner_firstDerivative_zero_of_stationary
#print axioms Zeta23.CCM.existsUnique_stationaryEvenResponse
#print axioms Zeta23.CCM.stationaryEvenResponse_spec
