import Zeta23.CCM.FirstCrossingProductionFirstVariation
import Zeta23.CCM.GlobalParityBottomSimplicity
import Zeta23.CCM.RankOneEigenline
import Mathlib.Analysis.InnerProductSpace.Symmetric

noncomputable section

namespace Zeta23.CCM

open Complex Set
open scoped ComplexConjugate

/-!
# Post-#281 strict-even stationary response

At a strict-even zero mode the source functional already proves that the even
zero eigenspace is a single line.  Self-adjointness of the production first
derivative turns stationarity into orthogonality of E'z to that line.  Finite
dimensional self-adjoint range/kernel geometry then constructs the unique
perpendicular response

  E w = -E' z,   <z,w> = 0.

No inverse on an uncertain complement and no arbitrary gauge choice is used.
-/

/-- The even zero eigenspace is exactly the line generated by any nonzero
strict-even zero eigenvector. -/
theorem strictEven_zeroKernel_is_line
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (x : euclideanEvenBoundaryFlatSubspace K)
    (hx : evenCompressedCanonical L K x = 0) :
    ∃ c : ℂ, c • z = x := by
  have hfaith :
      ∀ y : euclideanEvenBoundaryFlatSubspace K,
        evenCompressedCanonical L K y = (0 : ℂ) • y →
        cubicDefectFunctional L K y = 0 → y = 0 := by
    intro y hy hS
    exact evenEigenmode_eq_zero_of_source_eq_zero_below_odd
      hL K hK 0 hodd y hy hS
  have hz : evenCompressedCanonical L K z = (0 : ℂ) • z := by
    simpa using hzero
  have hx' : evenCompressedCanonical L K x = (0 : ℂ) • x := by
    simpa using hx
  exact eigenmode_eq_smul_of_functional_kernel
    (evenCompressedCanonical L K) (0 : ℂ)
    (cubicDefectFunctional L K) hfaith hz hzne x hx'

/-- Stationarity plus self-adjointness makes the derivative forcing exactly
orthogonal to the zero eigenvector, not merely zero in real part. -/
theorem inner_firstDerivative_zero_of_stationary
    {L : ℝ} (K : ℕ)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    inner ℂ
      (parityProductionApertureFirst .even L K z) z = 0 := by
  let a : ℂ :=
    inner ℂ (parityProductionApertureFirst .even L K z) z
  have hre : a.re = 0 := by
    simpa [a, productionContactFirstVariation] using hstationary
  have hsym :=
    parityProductionApertureFirst_isSymmetric .even L K z z
  have hstar : star a = a := by
    calc
      star a =
          inner ℂ z (parityProductionApertureFirst .even L K z) := by
            simpa [a] using
              (inner_conj_symm
                (parityProductionApertureFirst .even L K z) z)
      _ = a := by simpa [a] using hsym.symm
  have him : a.im = 0 := by
    have h := congrArg Complex.im hstar
    simp only [map_neg, starRingEnd_apply, Complex.star_def,
      Complex.conj_im] at h
    linarith
  apply Complex.ext
  · simpa [hre]
  · simpa [him]

/-- The stationary forcing lies in the range of the strict-even contact
operator. -/
theorem neg_firstDerivative_mem_evenRange_of_stationary_strict
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    -(parityProductionApertureFirst .even L K z) ∈
      (evenCompressedCanonical L K).range := by
  let E := evenCompressedCanonical L K
  let b := parityProductionApertureFirst .even L K z
  have hbz : inner ℂ b z = 0 := by
    simpa [b] using inner_firstDerivative_zero_of_stationary K z hstationary
  have hbker : b ∈ E.kerᗮ := by
    intro x hx
    have hx0 : E x = 0 := LinearMap.mem_ker.mp hx
    obtain ⟨c, hc⟩ :=
      strictEven_zeroKernel_is_line hL K hK z hzne hzero hodd x hx0
    rw [← hc]
    rw [inner_smul_left]
    simp [hbz]
  have hrangeOrth :
      E.rangeᗮ = E.ker :=
    (parityCompressedCanonical_isSymmetric .even L K).orthogonal_range
  have hrange : E.range = E.kerᗮ := by
    calc
      E.range = E.rangeᗮᗮ := by
        symm
        exact Submodule.orthogonal_orthogonal
      _ = E.kerᗮ := by rw [hrangeOrth]
  rw [hrange]
  exact E.kerᗮ.neg_mem hbker

/-- Existence and uniqueness of the normalized/perpendicular stationary
response. -/
theorem existsUnique_stationaryEvenResponse
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hznorm : ‖z‖ = 1)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    ∃! w : euclideanEvenBoundaryFlatSubspace K,
      inner ℂ z w = 0 ∧
      evenCompressedCanonical L K w =
        -(parityProductionApertureFirst .even L K z) := by
  let E := evenCompressedCanonical L K
  let b := parityProductionApertureFirst .even L K z
  have hmem :
      -b ∈ E.range := by
    simpa [E, b] using
      neg_firstDerivative_mem_evenRange_of_stationary_strict
        hL K hK z hzne hzero hodd hstationary
  obtain ⟨w0, hw0⟩ := hmem
  have hzz : inner ℂ z z = 1 := by
    rw [inner_self_eq_norm_sq_to_K, hznorm]
    norm_num
  let w : euclideanEvenBoundaryFlatSubspace K :=
    w0 - (inner ℂ z w0) • z
  have hwperp : inner ℂ z w = 0 := by
    dsimp [w]
    rw [inner_sub_right, inner_smul_right, hzz]
    simp
  have hwsolve : E w = -b := by
    dsimp [w]
    rw [map_sub, map_smul, hzero, smul_zero, sub_zero]
    exact hw0
  refine ⟨w, ⟨hwperp, by simpa [E, b] using hwsolve⟩, ?_⟩
  intro y hy
  have hdiff : E (y - w) = 0 := by
    rw [map_sub, hy.2, hwsolve, sub_self]
  obtain ⟨c, hc⟩ :=
    strictEven_zeroKernel_is_line
      hL K hK z hzne hzero hodd (y - w) hdiff
  have horth : inner ℂ z (y - w) = 0 := by
    rw [inner_sub_right, hy.1, hwperp, sub_self]
  have hc0 : c = 0 := by
    have h := congrArg (fun u => inner ℂ z u) hc
    rw [inner_smul_right, hzz, horth] at h
    simpa using h
  have hyw : y - w = 0 := by
    rw [← hc, hc0, zero_smul]
  exact sub_eq_zero.mp hyw

/-- Canonical chosen stationary response. -/
noncomputable def stationaryEvenResponse
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hznorm : ‖z‖ = 1)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    euclideanEvenBoundaryFlatSubspace K :=
  Classical.choose
    (existsUnique_stationaryEvenResponse
      hL K hK z hzne hznorm hzero hodd hstationary)

theorem stationaryEvenResponse_spec
    {L : ℝ} (hL : 0 < L)
    (K : ℕ) (hK : 2 ≤ K)
    (z : euclideanEvenBoundaryFlatSubspace K)
    (hzne : z ≠ 0)
    (hznorm : ‖z‖ = 1)
    (hzero : evenCompressedCanonical L K z = 0)
    (hodd : 0 < parityRayleighBottom .odd L K)
    (hstationary :
      productionContactFirstVariation .even L K z = 0) :
    inner ℂ z
        (stationaryEvenResponse hL K hK z hzne hznorm hzero hodd hstationary) = 0 ∧
      evenCompressedCanonical L K
        (stationaryEvenResponse hL K hK z hzne hznorm hzero hodd hstationary) =
          -(parityProductionApertureFirst .even L K z) :=
  (Classical.choose_spec
    (existsUnique_stationaryEvenResponse
      hL K hK z hzne hznorm hzero hodd hstationary)).1

end Zeta23.CCM

#print axioms Zeta23.CCM.strictEven_zeroKernel_is_line
#print axioms Zeta23.CCM.inner_firstDerivative_zero_of_stationary
#print axioms Zeta23.CCM.existsUnique_stationaryEvenResponse
#print axioms Zeta23.CCM.stationaryEvenResponse_spec
