import Zeta23.CCM.CanonicalSourceEnergyJets

noncomputable section

namespace Zeta23.CCM

open Complex Matrix Set
open scoped BigOperators ComplexConjugate

/-!
# FIRST-BAD-RIGIDITY-E4-A4-FB04C: mixed source derivative transport

This module introduces the complex mixed source pairing needed to connect the
quadratic-normal source observable to the production moment/Riesz boundary
layer.  The source-coordinate dependence is kept in the existing real analytic
shadow `sourceEntryReal`; the coefficient pairing is complex.

The rank-two second-derivative defect is retained in later theorems rather than
silently killed.  No sign, nonzeroness, branch exclusion, negative-root
exclusion, or RH claim is made here.
-/

/-- Complex mixed pairing generated by one elementary source matrix. -/
def sourceAtomPairing
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) : ℂ :=
  ∑ i, ∑ j,
    sourceEntryReal ω (centeredIndex K i) (centeredIndex K j) •
      (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
        (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- First source-coordinate derivative of the mixed pairing. -/
def sourceAtomPairingDerivative
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) : ℂ :=
  ∑ i, ∑ j,
    sourceEntryDerivative ω (centeredIndex K i) (centeredIndex K j) •
      (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
        (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- Second source-coordinate derivative of the mixed pairing. -/
def sourceAtomPairingSecondDerivative
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) : ℂ :=
  ∑ i, ∑ j,
    sourceEntrySecondDerivative ω (centeredIndex K i) (centeredIndex K j) •
      (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
        (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- Exact first derivative of the complex mixed source pairing. -/
theorem hasDerivAt_sourceAtomPairing
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) :
    HasDerivAt (sourceAtomPairing K x y)
      (sourceAtomPairingDerivative K x y ω) ω := by
  unfold sourceAtomPairing sourceAtomPairingDerivative
  apply HasDerivAt.fun_sum
  intro i hi
  apply HasDerivAt.fun_sum
  intro j hj
  exact
    (hasDerivAt_sourceEntryReal
      ω (centeredIndex K i) (centeredIndex K j)).smul_const
        (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
          (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- Exact second derivative of the complex mixed source pairing. -/
theorem hasDerivAt_sourceAtomPairingDerivative
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) :
    HasDerivAt (sourceAtomPairingDerivative K x y)
      (sourceAtomPairingSecondDerivative K x y ω) ω := by
  unfold sourceAtomPairingDerivative sourceAtomPairingSecondDerivative
  apply HasDerivAt.fun_sum
  intro i hi
  apply HasDerivAt.fun_sum
  intro j hj
  exact
    (hasDerivAt_sourceEntryDerivative
      ω (centeredIndex K i) (centeredIndex K j)).smul_const
        (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
          (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

end Zeta23.CCM

#print axioms Zeta23.CCM.hasDerivAt_sourceAtomPairing
#print axioms Zeta23.CCM.hasDerivAt_sourceAtomPairingDerivative
