import Zeta23.CCM.CanonicalSourceEnergyJets

noncomputable section

namespace Zeta23.CCM

open Complex Matrix Set
open scoped BigOperators ComplexConjugate

/-!
# FIRST-BAD-RIGIDITY-E4-A4-FB04C: mixed source derivative transport

This module introduces the complex mixed source pairing needed to connect the
quadratic-normal source observable to the production moment/Riesz boundary
layer.  The source-coordinate dependence is kept in the existing real analytic
shadow `sourceEntryReal`; the coefficient pairing is complex.

Unlike the self-energy transport, the mixed pairing has a rank-two defect when
only one coefficient sum vanishes.  We retain exactly the surviving right-hand
defect and use it to expose the third endpoint jet.  No sign, nonzeroness,
branch exclusion, negative-root exclusion, or RH claim is made here.
-/

/-- Complex mixed pairing generated by one elementary source matrix. -/
def sourceAtomPairing
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) : ℂ :=
  ∑ i, ∑ j,
    sourceEntryReal ω (centeredIndex K i) (centeredIndex K j) •
      (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
        (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- First source-coordinate derivative of the mixed pairing. -/
def sourceAtomPairingDerivative
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) : ℂ :=
  ∑ i, ∑ j,
    sourceEntryDerivative ω (centeredIndex K i) (centeredIndex K j) •
      (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
        (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- Second source-coordinate derivative of the mixed pairing. -/
def sourceAtomPairingSecondDerivative
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) : ℂ :=
  ∑ i, ∑ j,
    sourceEntrySecondDerivative ω (centeredIndex K i) (centeredIndex K j) •
      (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
        (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- Exact first derivative of the complex mixed source pairing. -/
theorem hasDerivAt_sourceAtomPairing
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) :
    HasDerivAt (sourceAtomPairing K x y)
      (sourceAtomPairingDerivative K x y ω) ω := by
  unfold sourceAtomPairing sourceAtomPairingDerivative
  apply HasDerivAt.fun_sum
  intro i hi
  apply HasDerivAt.fun_sum
  intro j hj
  exact
    (hasDerivAt_sourceEntryReal
      ω (centeredIndex K i) (centeredIndex K j)).smul_const
        (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
          (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- Exact second derivative of the complex mixed source pairing. -/
theorem hasDerivAt_sourceAtomPairingDerivative
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) :
    HasDerivAt (sourceAtomPairingDerivative K x y)
      (sourceAtomPairingSecondDerivative K x y ω) ω := by
  unfold sourceAtomPairingDerivative sourceAtomPairingSecondDerivative
  apply HasDerivAt.fun_sum
  intro i hi
  apply HasDerivAt.fun_sum
  intro j hj
  exact
    (hasDerivAt_sourceEntryDerivative
      ω (centeredIndex K i) (centeredIndex K j)).smul_const
        (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
          (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j))

/-- The coefficient sum used by the mixed transport. -/
def sourcePairingCoefficientSum
    (K : ℕ)
    (x : EuclideanSpace ℂ (Fin (2 * K + 1))) : ℂ :=
  ∑ i, ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i

/-- The surviving right rank-one factor in the mixed second-derivative defect. -/
def sourcePairingRightDefect
    (K : ℕ)
    (y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) : ℂ :=
  ∑ j,
    ((centeredIndex K j : ℝ) *
      Real.sin (2 * Real.pi * (centeredIndex K j : ℝ) * ω)) •
        ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j

private theorem sum_sum_pairing_factor
    {ι : Type*} [Fintype ι]
    (u v : ι → ℂ) :
    (∑ i, ∑ j, star (u i) * v j) =
      star (∑ i, u i) * (∑ j, v j) := by
  classical
  calc
    (∑ i, ∑ j, star (u i) * v j) =
        ∑ i, star (u i) * (∑ j, v j) := by
          apply Finset.sum_congr rfl
          intro i hi
          rw [Finset.mul_sum]
    _ = (∑ i, star (u i)) * (∑ j, v j) := by
          rw [Finset.sum_mul]
    _ = star (∑ i, u i) * (∑ j, v j) := by
          congr 1
          change
            (∑ i, (starRingEnd ℂ) (u i)) =
              (starRingEnd ℂ) (∑ i, u i)
          rw [map_sum]

private theorem sum_sum_real_smul
    {ι κ : Type*} [Fintype ι] [Fintype κ]
    (c : ℝ) (f : ι → κ → ℂ) :
    (∑ i, ∑ j, c • f i j) = c • (∑ i, ∑ j, f i j) := by
  classical
  symm
  rw [Finset.smul_sum]
  apply Finset.sum_congr rfl
  intro i hi
  rw [Finset.smul_sum]

private theorem sum_sum_left_weight_factor
    {ι : Type*} [Fintype ι]
    (a : ι → ℝ) (u v : ι → ℂ) :
    (∑ i, ∑ j, a i • (star (u i) * v j)) =
      (∑ i, a i • star (u i)) * (∑ j, v j) := by
  classical
  calc
    (∑ i, ∑ j, a i • (star (u i) * v j)) =
        ∑ i, a i • (star (u i) * (∑ j, v j)) := by
          apply Finset.sum_congr rfl
          intro i hi
          rw [Finset.mul_sum, Finset.smul_sum]
    _ = ∑ i, (a i • star (u i)) * (∑ j, v j) := by
          apply Finset.sum_congr rfl
          intro i hi
          simp only [Complex.real_smul]
          ring
    _ = (∑ i, a i • star (u i)) * (∑ j, v j) := by
          rw [Finset.sum_mul]

private theorem sum_sum_right_weight_factor
    {ι : Type*} [Fintype ι]
    (a : ι → ℝ) (u v : ι → ℂ) :
    (∑ i, ∑ j, a j • (star (u i) * v j)) =
      star (∑ i, u i) * (∑ j, a j • v j) := by
  classical
  rw [Finset.sum_comm]
  calc
    (∑ j, ∑ i, a j • (star (u i) * v j)) =
        ∑ j, a j • ((∑ i, star (u i)) * v j) := by
          apply Finset.sum_congr rfl
          intro j hj
          rw [Finset.sum_mul, Finset.smul_sum]
    _ = ∑ j, (∑ i, star (u i)) * (a j • v j) := by
          apply Finset.sum_congr rfl
          intro j hj
          simp only [Complex.real_smul]
          ring
    _ = (∑ i, star (u i)) * (∑ j, a j • v j) := by
          rw [Finset.mul_sum]
    _ = star (∑ i, u i) * (∑ j, a j • v j) := by
          congr 1
          change
            (∑ i, (starRingEnd ℂ) (u i)) =
              (starRingEnd ℂ) (∑ i, u i)
          rw [map_sum]

/-- Raw centered-index action written using the real scalar action on complex
coordinates.  It is proved equal to the existing production `sourceIndexAction`
below; the raw form keeps mixed-pairing algebra simple. -/
def sourcePairingIndexAction
    (K : ℕ)
    (x : EuclideanSpace ℂ (Fin (2 * K + 1))) :
    EuclideanSpace ℂ (Fin (2 * K + 1)) :=
  (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ).symm
    (fun i => (centeredIndex K i : ℝ) •
      ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i)

@[simp] theorem sourcePairingIndexAction_coordinates
    (K : ℕ)
    (x : EuclideanSpace ℂ (Fin (2 * K + 1))) :
    (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ)
        (sourcePairingIndexAction K x) =
      fun i => (centeredIndex K i : ℝ) •
        ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i := by
  unfold sourcePairingIndexAction
  exact (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ).apply_symm_apply _

/-- The raw mixed index action is the theorem-authoritative production index
action from #157. -/
theorem sourcePairingIndexAction_eq_sourceIndexAction
    (K : ℕ)
    (x : EuclideanSpace ℂ (Fin (2 * K + 1))) :
    sourcePairingIndexAction K x = sourceIndexAction K x := by
  apply (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ).injective
  rw [sourcePairingIndexAction_coordinates, sourceIndexAction_coordinates]
  ext i
  simp only [indexMatrix_mulVec_apply, Complex.real_smul]
  push_cast
  rfl

private theorem sourceAtomPairing_indexActions_raw
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ) :
    sourceAtomPairing K
        (sourcePairingIndexAction K x)
        (sourcePairingIndexAction K y) ω =
      ∑ i, ∑ j,
        ((centeredIndex K i : ℝ) * (centeredIndex K j : ℝ) *
          sourceEntryReal ω (centeredIndex K i) (centeredIndex K j)) •
            (star (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) i) *
              (((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) j)) := by
  unfold sourceAtomPairing
  rw [sourcePairingIndexAction_coordinates, sourcePairingIndexAction_coordinates]
  apply Finset.sum_congr rfl
  intro i hi
  apply Finset.sum_congr rfl
  intro j hj
  simp only [star_smul, star_trivial, Complex.real_smul]
  push_cast
  ring

/-- Exact mixed second-derivative transport when the right coefficient sum
vanishes.  The left rank-one term dies, while the right rank-one defect is
retained explicitly. -/
theorem sourceAtomPairingSecondDerivative_transport_of_right_sum_zero
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ)
    (hy0 : sourcePairingCoefficientSum K y = 0) :
    sourceAtomPairingSecondDerivative K x y ω =
      (-(2 * Real.pi) ^ 2 : ℝ) •
        sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y) ω -
      (4 * Real.pi) •
        (star (sourcePairingCoefficientSum K x) *
          sourcePairingRightDefect K y ω) := by
  let ux := (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x
  let uy := (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y
  let a : Fin (2 * K + 1) → ℝ := fun i =>
    (centeredIndex K i : ℝ) *
      Real.sin (2 * Real.pi * (centeredIndex K i : ℝ) * ω)
  have hmainRaw :
      (∑ i, ∑ j,
        (-(2 * Real.pi) ^ 2 * (centeredIndex K i : ℝ) *
          (centeredIndex K j : ℝ) *
          sourceEntryReal ω (centeredIndex K i) (centeredIndex K j)) •
            (star (ux i) * uy j)) =
        (-(2 * Real.pi) ^ 2 : ℝ) •
          sourceAtomPairing K
            (sourcePairingIndexAction K x)
            (sourcePairingIndexAction K y) ω := by
    have hidx := sourceAtomPairing_indexActions_raw K x y ω
    rw [hidx]
    rw [Finset.smul_sum]
    apply Finset.sum_congr rfl
    intro i hi
    rw [Finset.smul_sum]
    apply Finset.sum_congr rfl
    intro j hj
    simp only [Complex.real_smul]
    push_cast
    ring
  have hleft :
      (∑ i, ∑ j, a i • (star (ux i) * uy j)) = 0 := by
    rw [sum_sum_left_weight_factor]
    change (∑ i, a i • star (ux i)) * sourcePairingCoefficientSum K y = 0
    rw [hy0, mul_zero]
  have hright :
      (∑ i, ∑ j, a j • (star (ux i) * uy j)) =
        star (sourcePairingCoefficientSum K x) *
          sourcePairingRightDefect K y ω := by
    simpa [sourcePairingCoefficientSum, sourcePairingRightDefect, ux, uy, a] using
      sum_sum_right_weight_factor a ux uy
  unfold sourceAtomPairingSecondDerivative
  simp_rw [sourceEntrySecondDerivative_transport]
  simp_rw [sub_smul, Finset.sum_sub_distrib]
  rw [hmainRaw]
  have hrank :
      (∑ i, ∑ j,
        (4 * Real.pi * (a i + a j)) • (star (ux i) * uy j)) =
        (4 * Real.pi) •
          ((∑ i, ∑ j, a i • (star (ux i) * uy j)) +
            (∑ i, ∑ j, a j • (star (ux i) * uy j))) := by
    calc
      (∑ i, ∑ j,
        (4 * Real.pi * (a i + a j)) • (star (ux i) * uy j)) =
          ∑ i, ∑ j,
            (4 * Real.pi) •
              ((a i + a j) • (star (ux i) * uy j)) := by
                apply Finset.sum_congr rfl
                intro i hi
                apply Finset.sum_congr rfl
                intro j hj
                rw [mul_smul]
      _ = (4 * Real.pi) •
          (∑ i, ∑ j, (a i + a j) • (star (ux i) * uy j)) := by
            exact sum_sum_real_smul (4 * Real.pi)
              (fun i j => (a i + a j) • (star (ux i) * uy j))
      _ = _ := by
            congr 1
            simp_rw [add_smul, Finset.sum_add_distrib]
  rw [show
    (∑ i, ∑ j,
      (4 * Real.pi *
        ((centeredIndex K i : ℝ) *
            Real.sin (2 * Real.pi * (centeredIndex K i : ℝ) * ω) +
          (centeredIndex K j : ℝ) *
            Real.sin (2 * Real.pi * (centeredIndex K j : ℝ) * ω))) •
        (star (ux i) * uy j)) =
      (∑ i, ∑ j,
        (4 * Real.pi * (a i + a j)) • (star (ux i) * uy j)) by rfl]
  rw [hrank, hleft, zero_add, hright]
  rw [sourcePairingIndexAction_eq_sourceIndexAction,
    sourcePairingIndexAction_eq_sourceIndexAction]

/-- If both coefficient sums vanish, the entire mixed rank-two defect dies and
two source derivatives become one index action on each argument. -/
theorem sourceAtomPairingSecondDerivative_eq_indexActions
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ)
    (hx0 : sourcePairingCoefficientSum K x = 0)
    (hy0 : sourcePairingCoefficientSum K y = 0) :
    sourceAtomPairingSecondDerivative K x y ω =
      (-(2 * Real.pi) ^ 2 : ℝ) •
        sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y) ω := by
  rw [sourceAtomPairingSecondDerivative_transport_of_right_sum_zero K x y ω hy0,
    hx0]
  simp

/-- The first endpoint derivative factors through the two complex coefficient
sums. -/
theorem sourceAtomPairingDerivative_zero_eq_two_sum_pairing
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1))) :
    sourceAtomPairingDerivative K x y 0 =
      (2 : ℝ) •
        (star (sourcePairingCoefficientSum K x) *
          sourcePairingCoefficientSum K y) := by
  let ux := (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x
  let uy := (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y
  unfold sourceAtomPairingDerivative
  simp_rw [sourceEntryDerivative_zero]
  calc
    (∑ i, ∑ j, (2 : ℝ) • (star (ux i) * uy j)) =
        (2 : ℝ) • (∑ i, ∑ j, star (ux i) * uy j) := by
          exact sum_sum_real_smul 2 (fun i j => star (ux i) * uy j)
    _ = (2 : ℝ) • (star (∑ i, ux i) * (∑ j, uy j)) := by
          rw [sum_sum_pairing_factor]
    _ = _ := by
          rfl

/-- The right rank-one defect has derivative `2*pi*M_2` at the source endpoint. -/
theorem hasDerivAt_sourcePairingRightDefect_zero
    (K : ℕ)
    (y : EuclideanSpace ℂ (Fin (2 * K + 1))) :
    HasDerivAt (sourcePairingRightDefect K y)
      ((2 * Real.pi : ℝ) •
        centeredMoment K 2
          ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y)) 0 := by
  let uy := (EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y
  have hsum :
      HasDerivAt (sourcePairingRightDefect K y)
        (∑ j,
          (2 * Real.pi * (centeredIndex K j : ℝ) ^ 2) • uy j) 0 := by
    unfold sourcePairingRightDefect
    apply HasDerivAt.fun_sum
    intro j hj
    have harg : HasDerivAt
        (fun t : ℝ => 2 * Real.pi * (centeredIndex K j : ℝ) * t)
        (2 * Real.pi * (centeredIndex K j : ℝ)) 0 := by
      simpa using
        (hasDerivAt_id (0 : ℝ)).const_mul
          (2 * Real.pi * (centeredIndex K j : ℝ))
    have hsin := harg.sin
    have hweighted := hsin.const_mul (centeredIndex K j : ℝ)
    have hterm := hweighted.smul_const (uy j)
    convert hterm using 1 <;> simp <;> ring
  convert hsum using 1
  unfold centeredMoment
  rw [Finset.smul_sum]
  apply Finset.sum_congr rfl
  intro j hj
  simp only [Complex.real_smul]
  push_cast
  ring

/-- Two source derivatives transport to one index action on each argument when
both coefficient sums vanish. -/
theorem iteratedDeriv_two_sourceAtomPairing_eq_indexActions
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (ω : ℝ)
    (hx0 : sourcePairingCoefficientSum K x = 0)
    (hy0 : sourcePairingCoefficientSum K y = 0) :
    iteratedDeriv 2 (sourceAtomPairing K x y) ω =
      (-(2 * Real.pi) ^ 2 : ℝ) •
        sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y) ω := by
  rw [show 2 = 1 + 1 by omega, iteratedDeriv_succ, iteratedDeriv_one]
  have hderiv :
      deriv (sourceAtomPairing K x y) = sourceAtomPairingDerivative K x y := by
    funext t
    exact (hasDerivAt_sourceAtomPairing K x y t).deriv
  rw [hderiv]
  rw [(hasDerivAt_sourceAtomPairingDerivative K x y ω).deriv]
  exact sourceAtomPairingSecondDerivative_eq_indexActions K x y ω hx0 hy0

/-- General two-step transport for higher mixed source jets under the same
zero-sum hypotheses. -/
theorem iteratedDeriv_add_two_sourceAtomPairing_eq_indexActions
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (j : ℕ)
    (ω : ℝ)
    (hx0 : sourcePairingCoefficientSum K x = 0)
    (hy0 : sourcePairingCoefficientSum K y = 0) :
    iteratedDeriv (j + 2) (sourceAtomPairing K x y) ω =
      (-(2 * Real.pi) ^ 2 : ℝ) •
        iteratedDeriv j
          (sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y)) ω := by
  have htwo :
      iteratedDeriv 2 (sourceAtomPairing K x y) =
        fun t => (-(2 * Real.pi) ^ 2 : ℝ) •
          sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y) t := by
    funext t
    exact iteratedDeriv_two_sourceAtomPairing_eq_indexActions K x y t hx0 hy0
  calc
    iteratedDeriv (j + 2) (sourceAtomPairing K x y) ω =
        iteratedDeriv j (iteratedDeriv 2 (sourceAtomPairing K x y)) ω := by
          simp only [iteratedDeriv_eq_iterate]
          exact congrFun
            (Function.iterate_add_apply
              (fun f : ℝ → ℂ => deriv f) j 2 (sourceAtomPairing K x y)) ω
    _ = iteratedDeriv j
        (fun t => (-(2 * Real.pi) ^ 2 : ℝ) •
          sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y) t) ω := by
          rw [htwo]
    _ = (-(2 * Real.pi) ^ 2 : ℝ) •
        iteratedDeriv j
          (sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y)) ω := by
          simpa using
            (iteratedDeriv_const_smul_field
              (x := ω) (n := j)
              (-(2 * Real.pi) ^ 2 : ℝ)
              (sourceAtomPairing K (sourceIndexAction K x) (sourceIndexAction K y)))

/-- The exact third endpoint jet when the right coefficient sum vanishes.  This
is the mixed analogue needed at the final transport step: the surviving terms
are `conj(M1(x))*M1(y)` and `conj(M0(x))*M2(y)`. -/
theorem iteratedDeriv_three_sourceAtomPairing_eq_moments_of_right_sum_zero
    (K : ℕ)
    (x y : EuclideanSpace ℂ (Fin (2 * K + 1)))
    (hy0 : sourcePairingCoefficientSum K y = 0) :
    iteratedDeriv 3 (sourceAtomPairing K x y) 0 =
      ((-2 * (2 * Real.pi) ^ 2 : ℝ) : ℂ) *
        (star
            (centeredMoment K 1
              ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x)) *
            centeredMoment K 1
              ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) +
          star
            (centeredMoment K 0
              ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x)) *
            centeredMoment K 2
              ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y)) := by
  let sx := sourcePairingCoefficientSum K x
  let Dx := sourceIndexAction K x
  let Dy := sourceIndexAction K y
  have htransport :
      sourceAtomPairingSecondDerivative K x y =
        fun t =>
          (-(2 * Real.pi) ^ 2 : ℝ) • sourceAtomPairing K Dx Dy t -
            (4 * Real.pi) •
              (star sx * sourcePairingRightDefect K y t) := by
    funext t
    simpa [sx, Dx, Dy] using
      sourceAtomPairingSecondDerivative_transport_of_right_sum_zero K x y t hy0
  have hpDer := hasDerivAt_sourceAtomPairing K Dx Dy 0
  have hp0 := sourceAtomPairingDerivative_zero_eq_two_sum_pairing K Dx Dy
  have hR := hasDerivAt_sourcePairingRightDefect_zero K y
  have hrightMul := hR.const_mul (star sx)
  have htotal : HasDerivAt
      (sourceAtomPairingSecondDerivative K x y)
      ((-(2 * Real.pi) ^ 2 : ℝ) • sourceAtomPairingDerivative K Dx Dy 0 -
        (4 * Real.pi) •
          (star sx *
            ((2 * Real.pi : ℝ) •
              centeredMoment K 2
                ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y)))) 0 := by
    rw [htransport]
    exact (hpDer.const_smul (-(2 * Real.pi) ^ 2 : ℝ)).sub
      (hrightMul.const_smul (4 * Real.pi))
  have htwoFun :
      iteratedDeriv 2 (sourceAtomPairing K x y) =
        sourceAtomPairingSecondDerivative K x y := by
    funext t
    rw [show 2 = 1 + 1 by omega, iteratedDeriv_succ, iteratedDeriv_one]
    have hderiv :
        deriv (sourceAtomPairing K x y) = sourceAtomPairingDerivative K x y := by
      funext s
      exact (hasDerivAt_sourceAtomPairing K x y s).deriv
    rw [hderiv]
    exact (hasDerivAt_sourceAtomPairingDerivative K x y t).deriv
  rw [show 3 = 2 + 1 by omega, iteratedDeriv_succ, htwoFun, htotal.deriv]
  rw [hp0]
  have hsx0 : sx = centeredMoment K 0
      ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) := by
    symm
    simpa [sx, sourcePairingCoefficientSum] using
      centeredMoment_zero_eq_sum K
        ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x)
  have hsumDx : sourcePairingCoefficientSum K Dx =
      centeredMoment K 1
        ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) x) := by
    rw [← centeredMoment_zero_eq_sum]
    simpa [Dx] using centeredMoment_sourceIndexAction K 0 x
  have hsumDy : sourcePairingCoefficientSum K Dy =
      centeredMoment K 1
        ((EuclideanSpace.equiv (Fin (2 * K + 1)) ℂ) y) := by
    rw [← centeredMoment_zero_eq_sum]
    simpa [Dy] using centeredMoment_sourceIndexAction K 0 y
  rw [hsumDx, hsumDy, hsx0]
  simp only [Complex.real_smul]
  push_cast
  ring

end Zeta23.CCM

#print axioms Zeta23.CCM.hasDerivAt_sourceAtomPairing
#print axioms Zeta23.CCM.sourceAtomPairingSecondDerivative_transport_of_right_sum_zero
#print axioms Zeta23.CCM.sourceAtomPairingSecondDerivative_eq_indexActions
#print axioms Zeta23.CCM.hasDerivAt_sourcePairingRightDefect_zero
#print axioms Zeta23.CCM.iteratedDeriv_add_two_sourceAtomPairing_eq_indexActions
#print axioms Zeta23.CCM.iteratedDeriv_three_sourceAtomPairing_eq_moments_of_right_sum_zero
