import Zeta23.CCM.ParityCompressionRankOne
import Zeta23.CCM.FirstBadIntrinsicBlock

noncomputable section

namespace Zeta23.CCM

open Matrix Set
open scoped BigOperators ComplexConjugate

/-!
# FIRST-BAD-RIGIDITY-D1: exact cubic defect factorization

PR #110 proved that every value of the compressed even-to-odd intertwining
defect lies in the explicit line generated by `oddCubicCompressionVector N`.
For `N >= 2` that generator is nonzero, so its scalar coefficient can be
chosen canonically by orthogonal coordinate extraction.

The result is an exact one-channel factorization.  The scalar functional is
not asserted to be nonzero, so this does not upgrade rank-at-most-one to exact
rank one.  The D-equivalence remains algebraic, not unitary.
-/

/-- Canonical scalar coefficient of the parity defect along the cubic channel.
The definition makes sense at every N; `N >= 2` is needed only when proving
that the cubic generator is nonzero and hence that this coordinate recovers
the defect exactly.  Mathlib's complex inner product is linear in the second
argument, so this is a complex-linear functional of the even constrained
input. -/
def cubicDefectFunctional
    (L : ℝ) (N : ℕ) :
    euclideanEvenBoundaryFlatSubspace N →ₗ[ℂ] ℂ where
  toFun := fun v =>
    inner ℂ (oddCubicCompressionVector N)
        (evenOddCompressedIntertwiningDefect L N v) /
      inner ℂ (oddCubicCompressionVector N)
        (oddCubicCompressionVector N)
  map_add' := by
    intro x y
    simp only [map_add, inner_add_right]
    ring
  map_smul' := by
    intro c x
    simp [inner_smul_right, div_eq_mul_inv, mul_left_comm, mul_comm]

/-- Exact pointwise factorization through the cubic channel.  No nonzeroness
of the scalar functional is claimed. -/
theorem evenOddCompressedIntertwiningDefect_eq_cubicFunctional_smul
    {L : ℝ} (hL : 0 < L)
    (N : ℕ) (hN : 2 ≤ N)
    (v : euclideanEvenBoundaryFlatSubspace N) :
    evenOddCompressedIntertwiningDefect L N v =
      cubicDefectFunctional L N v • oddCubicCompressionVector N := by
  obtain ⟨a, ha⟩ :=
    exists_evenOddCompressedIntertwiningDefect_eq_smul_cubic hL N v
  have hg : oddCubicCompressionVector N ≠ 0 :=
    oddCubicCompressionVector_ne_zero N hN
  have hgg :
      inner ℂ (oddCubicCompressionVector N)
          (oddCubicCompressionVector N) ≠ 0 := by
    intro hzero
    apply hg
    exact (inner_self_eq_zero.mp hzero)
  have hcoeff : cubicDefectFunctional L N v = a := by
    change
      inner ℂ (oddCubicCompressionVector N)
          (evenOddCompressedIntertwiningDefect L N v) /
        inner ℂ (oddCubicCompressionVector N)
          (oddCubicCompressionVector N) = a
    rw [ha]
    simpa only [inner_smul_right] using
      (mul_div_cancel_right₀ a hgg)
  rw [ha, hcoeff]

/-- Cubic channel transported back to the even constrained carrier through
#110's algebraic D-equivalence.  This is a definition only; no metric
compatibility is asserted. -/
def pulledBackCubicCompressionVector
    (N : ℕ) (hN : 2 ≤ N) :
    euclideanEvenBoundaryFlatSubspace N :=
  (euclideanEvenOddBoundaryFlatLinearEquiv N (by omega)).symm
    (oddCubicCompressionVector N)

/-- The pulled-back cubic channel is nonzero because D is an algebraic linear
equivalence and the odd cubic channel is nonzero. -/
theorem pulledBackCubicCompressionVector_ne_zero
    (N : ℕ) (hN : 2 ≤ N) :
    pulledBackCubicCompressionVector N hN ≠ 0 := by
  intro hz
  apply oddCubicCompressionVector_ne_zero N hN
  have hmap := congrArg
    (euclideanEvenOddBoundaryFlatLinearEquiv N (by omega)) hz
  simpa [pulledBackCubicCompressionVector] using hmap

/-- Same-space pointwise factorization after algebraically conjugating the odd
compression back to the even carrier. -/
theorem conjugatedParityCompressionDefect_eq_cubicFunctional_smul
    {L : ℝ} (hL : 0 < L)
    (N : ℕ) (hN : 2 ≤ N)
    (v : euclideanEvenBoundaryFlatSubspace N) :
    conjugatedParityCompressionDefect L N (by omega) v =
      cubicDefectFunctional L N v •
        pulledBackCubicCompressionVector N hN := by
  let E := euclideanEvenOddBoundaryFlatLinearEquiv N (by omega)
  have hF :=
    evenOddCompressedIntertwiningDefect_eq_cubicFunctional_smul
      hL N hN v
  have hdef :
      conjugatedParityCompressionDefect L N (by omega) v =
        E.symm (evenOddCompressedIntertwiningDefect L N v) := by
    change
      E.symm (oddCompressedCanonical L N (E v)) -
          evenCompressedCanonical L N v =
        E.symm
          (oddCompressedCanonical L N (E v) -
            E (evenCompressedCanonical L N v))
    rw [map_sub, E.symm_apply_apply]
  rw [hdef, hF, map_smul]
  simp [pulledBackCubicCompressionVector, E]

end Zeta23.CCM

#print axioms Zeta23.CCM.evenOddCompressedIntertwiningDefect_eq_cubicFunctional_smul
#print axioms Zeta23.CCM.pulledBackCubicCompressionVector_ne_zero
#print axioms Zeta23.CCM.conjugatedParityCompressionDefect_eq_cubicFunctional_smul
