import Zeta23.ExceptionalZero.RegularFirstBadClosure
import Zeta23.Statement.SeamClosed
import Mathlib.NumberTheory.LSeries.Nonvanishing
import Mathlib.NumberTheory.LSeries.HurwitzZetaValues

noncomputable section

namespace Zeta23.ExceptionalZero

open Complex
open Zeta23.CCM

/-!
# Experimental terminal RH configuration attempt

This module intentionally does **not** claim RH.  It asks how short the final
Lean theorem becomes after composing the current off-line-zero -> retained
first-bad certificate chain with Mathlib's exact `RiemannHypothesis` statement.

The live RH-specific terminal interface is isolated as one finite proposition:
no retained regular cell-minimal negative-energy certificate can exist.

The rest of this module attacks the statement seam directly:
* zeros cannot lie on or to the right of `Re s = 1`;
* away from non-positive integers, the functional equation excludes
  `Re s <= 0`;
* negative odd integers are not zeros, using Mathlib's Bernoulli special-value
  formula plus nonvanishing of zeta at positive even integers.

No `sorry`, project axiom, hidden RH assumption, or theorem promotion is used.
-/

/-- Exact finite-side terminal obstruction needed by the current route.

This is a strong endpoint: it excludes every retained regular first-bad
certificate, not merely those generated by a hypothetical off-line zero.
The historical route notes already flag that a generated-certificate-specific
contradiction could be weaker. -/
def NoRegularFirstBadCertificates : Prop :=
  ∀ Q : ℕ, ∀ c : RegularCellMinimalNegativeEnergyCertificate Q, False

/-- Current theorem stack + exclusion of every retained regular first-bad
certificate implies the repository's strip-zero form of RH. -/
theorem criticalLine_of_noRegularFirstBadCertificates
    (hno : NoRegularFirstBadCertificates) :
    ∀ ρ ∈ zetaZeroConfig.carrier, ρ.re = 1 / 2 := by
  intro ρ hρ
  by_contra hoff
  obtain ⟨Q, hc⟩ :=
    exists_regularFirstBad_negativeEnergyCertificate_of_offLine_zero
      ⟨ρ, hρ⟩ hoff
  obtain ⟨c⟩ := hc
  exact hno Q c

/-! ## Terminal Mathlib statement seam -/

/-- A zeta zero cannot have real part at least one. -/
theorem re_lt_one_of_riemannZeta_zero
    {s : ℂ}
    (hz : riemannZeta s = 0) :
    s.re < 1 := by
  by_contra h
  have hge : 1 ≤ s.re := le_of_not_gt h
  exact (riemannZeta_ne_zero_of_one_le_re hge) hz

/-- Away from non-positive integers, a zeta zero cannot have non-positive real
part: reflect it through the functional equation to a zero with real part at
least one, contradicting Mathlib nonvanishing. -/
theorem re_pos_of_riemannZeta_zero_of_not_neg_nat
    {s : ℂ}
    (hz : riemannZeta s = 0)
    (hneg : ∀ n : ℕ, s ≠ -(n : ℂ)) :
    0 < s.re := by
  by_contra h
  have hle : s.re ≤ 0 := le_of_not_gt h
  have hs1 : s ≠ 1 := by
    intro hs
    subst s
    norm_num at hle
  have hreflect :
      riemannZeta (1 - s) = 0 := by
    rw [riemannZeta_one_sub hneg hs1, hz]
    simp
  have hre : 1 ≤ (1 - s).re := by
    simp only [Complex.sub_re, Complex.one_re]
    linarith
  exact (riemannZeta_ne_zero_of_one_le_re hre) hreflect

/-- Positive even Bernoulli indices are nonzero.

Rather than importing a Bernoulli sign theorem, we read this directly off
Mathlib's exact formula for zeta at positive even integers and the already
proved nonvanishing of zeta on `Re s >= 1`. -/
theorem bernoulli_two_mul_ne_zero
    (k : ℕ)
    (hk : k ≠ 0) :
    bernoulli (2 * k) ≠ 0 := by
  intro hb
  have hz := riemannZeta_two_mul_nat (k := k) hk
  rw [hb] at hz
  simp at hz
  have hk1 : 1 ≤ k := Nat.one_le_iff_ne_zero.mpr hk
  have hnat : 1 ≤ 2 * k := by omega
  have hreReal : (1 : ℝ) ≤ (2 * k : ℕ) := by
    exact_mod_cast hnat
  have hre : (1 : ℝ) ≤ ((2 * k : ℕ) : ℂ).re := by
    simpa using hreReal
  exact (riemannZeta_ne_zero_of_one_le_re hre) hz

/-- Zeta is nonzero at every negative odd integer. -/
theorem riemannZeta_neg_odd_ne_zero
    (k : ℕ) :
    riemannZeta (-(2 * k + 1 : ℂ)) ≠ 0 := by
  rw [riemannZeta_neg_nat_eq_bernoulli]
  apply div_ne_zero
  · apply mul_ne_zero
    · exact pow_ne_zero _ (by norm_num)
    · have hbq : bernoulli (2 * k + 1 + 1) ≠ 0 := by
        rw [show 2 * k + 1 + 1 = 2 * (k + 1) by omega]
        exact bernoulli_two_mul_ne_zero (k + 1) (by omega)
      exact_mod_cast hbq
  · exact_mod_cast (show 2 * k + 1 + 1 ≠ 0 by omega)

/-- The only non-positive integer zeros of zeta are the standard negative even
trivial zeros. -/
theorem negativeIntegerZeroClassification
    (n : ℕ)
    (hz : riemannZeta (-(n : ℂ)) = 0) :
    ∃ m : ℕ, (-(n : ℂ)) = -2 * (m + 1) := by
  rcases Nat.even_or_odd' n with ⟨k, (rfl | rfl)⟩
  · by_cases hk : k = 0
    · subst k
      norm_num [riemannZeta_zero] at hz
    · obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hk
      refine ⟨m, ?_⟩
      push_cast
      ring
  · exact (riemannZeta_neg_odd_ne_zero k hz).elim

/-- Mathlib's "nontrivial zero" hypotheses imply the repository's open-strip
`IsNontrivialZero`.  This discharges the terminal statement seam without any
RH-specific finite input. -/
theorem isNontrivialZero_of_mathlib_nontrivialZero
    {s : ℂ}
    (hz : riemannZeta s = 0)
    (htriv : ¬ ∃ n : ℕ, s = -2 * (n + 1))
    (_hs1 : s ≠ 1) :
    IsNontrivialZero s := by
  refine ⟨hz, ?_, re_lt_one_of_riemannZeta_zero hz⟩
  by_cases hnegNat : ∃ n : ℕ, s = -(n : ℂ)
  · obtain ⟨n, hn⟩ := hnegNat
    subst s
    exfalso
    exact htriv (negativeIntegerZeroClassification n hz)
  · exact re_pos_of_riemannZeta_zero_of_not_neg_nat hz
      (fun n hn => hnegNat ⟨n, hn⟩)

/-- **Experimental terminal configuration theorem.**

If the current retained finite obstruction is closed by proving
`NoRegularFirstBadCertificates`, the remainder of the repository already
composes to Mathlib's exact `RiemannHypothesis` statement. -/
theorem riemannHypothesis_of_noRegularFirstBadCertificates
    (hno : NoRegularFirstBadCertificates) :
    RiemannHypothesis := by
  intro s hz htriv hs1
  have hs :
      IsNontrivialZero s :=
    isNontrivialZero_of_mathlib_nontrivialZero hz htriv hs1
  have hmem : s ∈ zetaZeroConfig.carrier := by
    simpa using hs
  exact criticalLine_of_noRegularFirstBadCertificates hno s hmem

end Zeta23.ExceptionalZero

#print axioms Zeta23.ExceptionalZero.criticalLine_of_noRegularFirstBadCertificates
#print axioms Zeta23.ExceptionalZero.re_lt_one_of_riemannZeta_zero
#print axioms Zeta23.ExceptionalZero.re_pos_of_riemannZeta_zero_of_not_neg_nat
#print axioms Zeta23.ExceptionalZero.bernoulli_two_mul_ne_zero
#print axioms Zeta23.ExceptionalZero.riemannZeta_neg_odd_ne_zero
#print axioms Zeta23.ExceptionalZero.negativeIntegerZeroClassification
#print axioms Zeta23.ExceptionalZero.isNontrivialZero_of_mathlib_nontrivialZero
#print axioms Zeta23.ExceptionalZero.riemannHypothesis_of_noRegularFirstBadCertificates
